import { LIBRARY } from "./catalog";
import type {
  CommunityPost,
  Food,
  Friend,
  Goal,
  Ingredient,
  Place,
  Recipe,
  Wearable,
  Workout,
} from "./types";

export const GOALS: Goal[] = [
  {
    id: "cut",
    name: "Cut",
    blurb: "High protein, a mild deficit, training that keeps muscle.",
    kcal: 1900,
    protein: 165,
    carbs: 160,
    fat: 55,
    waterMl: 3200,
  },
  {
    id: "recomp",
    name: "Recomp",
    blurb: "Hold weight, raise training quality, eat to recover.",
    kcal: 2300,
    protein: 170,
    carbs: 220,
    fat: 70,
    waterMl: 3000,
  },
  {
    id: "bulk",
    name: "Lean bulk",
    blurb: "A small surplus with enough carbs to push heavy days.",
    kcal: 2900,
    protein: 185,
    carbs: 320,
    fat: 80,
    waterMl: 3400,
  },
  {
    id: "endurance",
    name: "Endurance",
    blurb: "Fuel long sessions, protect sleep, replace electrolytes.",
    kcal: 2700,
    protein: 140,
    carbs: 360,
    fat: 70,
    waterMl: 3800,
  },
  {
    id: "longevity",
    name: "Longevity",
    blurb: "Fiber, plants, zone 2, and a boringly good bedtime.",
    kcal: 2100,
    protein: 130,
    carbs: 220,
    fat: 70,
    waterMl: 3000,
  },
];

export const WEARABLES: Wearable[] = [
  {
    id: "healthkit",
    name: "Apple Health / HealthKit",
    maker: "Apple",
    platforms: ["ios"],
    metrics: ["HRV", "HR", "Sleep", "Workouts", "Steps", "VO2"],
    kind: "platform",
  },
  {
    id: "health-connect",
    name: "Health Connect",
    maker: "Google",
    platforms: ["android"],
    metrics: ["HRV", "HR", "Sleep", "Workouts", "Steps"],
    kind: "platform",
  },
  {
    id: "apple-watch",
    name: "Apple Watch",
    maker: "Apple",
    platforms: ["ios"],
    metrics: ["HRV", "HR", "Sleep", "Workouts", "SpO2", "Temp"],
    kind: "watch",
  },
  {
    id: "garmin",
    name: "Garmin",
    maker: "Garmin",
    platforms: ["ios", "android"],
    metrics: ["HRV", "Sleep", "Training load", "GPS", "Pulse ox"],
    kind: "watch",
  },
  {
    id: "oura",
    name: "Oura Ring",
    maker: "Oura",
    platforms: ["ios", "android"],
    metrics: ["HRV", "Sleep stages", "Temp", "Readiness"],
    kind: "ring",
  },
  {
    id: "whoop",
    name: "WHOOP",
    maker: "WHOOP",
    platforms: ["ios", "android"],
    metrics: ["Recovery", "Strain", "Sleep", "HRV"],
    kind: "band",
  },
  {
    id: "fitbit",
    name: "Fitbit / Pixel Watch",
    maker: "Google",
    platforms: ["ios", "android"],
    metrics: ["Sleep", "HR", "SpO2", "Steps"],
    kind: "watch",
  },
  {
    id: "samsung",
    name: "Samsung Health / Galaxy Watch",
    maker: "Samsung",
    platforms: ["android", "ios"],
    metrics: ["Sleep", "HRV", "BIA", "Workouts"],
    kind: "watch",
  },
  {
    id: "polar",
    name: "Polar",
    maker: "Polar",
    platforms: ["ios", "android"],
    metrics: ["HR", "Training load", "Nightly recharge"],
    kind: "watch",
  },
  {
    id: "coros",
    name: "COROS",
    maker: "COROS",
    platforms: ["ios", "android"],
    metrics: ["GPS", "Training load", "HR", "Sleep"],
    kind: "watch",
  },
  {
    id: "suunto",
    name: "Suunto",
    maker: "Suunto",
    platforms: ["ios", "android"],
    metrics: ["GPS", "HR", "Recovery"],
    kind: "watch",
  },
  {
    id: "amazfit",
    name: "Amazfit / Zepp",
    maker: "Zepp Health",
    platforms: ["ios", "android"],
    metrics: ["SpO2", "Sleep", "HR", "Stress"],
    kind: "watch",
  },
  {
    id: "withings",
    name: "Withings",
    maker: "Withings",
    platforms: ["ios", "android"],
    metrics: ["Weight", "Sleep", "BP", "ECG"],
    kind: "scale",
  },
  {
    id: "ultrahuman",
    name: "Ultrahuman Ring AIR",
    maker: "Ultrahuman",
    platforms: ["ios", "android"],
    metrics: ["HRV", "Sleep", "Glucose partner", "Temp"],
    kind: "ring",
  },
  {
    id: "xiaomi",
    name: "Xiaomi Wear / Mi Fitness",
    maker: "Xiaomi",
    platforms: ["android", "ios"],
    metrics: ["HR", "Sleep", "SpO2", "Steps"],
    kind: "band",
  },
  {
    id: "huawei",
    name: "Huawei Health",
    maker: "Huawei",
    platforms: ["android"],
    metrics: ["HR", "Sleep", "TruSleep", "SpO2"],
    kind: "watch",
  },
  {
    id: "strava-source",
    name: "Strava",
    maker: "Strava",
    platforms: ["ios", "android"],
    metrics: ["GPS", "Runs", "Rides", "Segments"],
    kind: "platform",
  },
];

export const WORKOUTS: Workout[] = LIBRARY;

export const PLACES: Place[] = [
  {
    id: "gym-equinox",
    name: "Equinox Sports Club",
    kind: "gym",
    lat: 37.7866,
    lng: -122.4041,
    area: "Union Square",
    hours: "5:00–23:00",
    rating: 4.6,
    tags: ["Strength", "Classes", "Recovery"],
  },
  {
    id: "gym-fitnesssf",
    name: "Fitness SF SOMA",
    kind: "gym",
    lat: 37.7812,
    lng: -122.3984,
    area: "SOMA",
    hours: "5:00–22:00",
    rating: 4.4,
    tags: ["Open gym", "Parking"],
  },
  {
    id: "gym-barrys",
    name: "Barry's Embarcadero",
    kind: "gym",
    lat: 37.7981,
    lng: -122.3967,
    area: "Embarcadero",
    hours: "5:30–20:00",
    rating: 4.7,
    tags: ["HIIT", "Treadmills"],
  },
  {
    id: "gym-planet",
    name: "Planet Fitness Market",
    kind: "gym",
    lat: 37.7753,
    lng: -122.4192,
    area: "Civic Center",
    hours: "24h",
    rating: 4.1,
    tags: ["Budget", "24h"],
  },
  {
    id: "gym-crossfit",
    name: "CrossFit Golden Gate",
    kind: "gym",
    lat: 37.7699,
    lng: -122.4258,
    area: "Castro",
    hours: "5:30–20:30",
    rating: 4.8,
    tags: ["Olympic", "Community"],
  },
  {
    id: "gym-boulders",
    name: "Dogpatch Boulders",
    kind: "gym",
    lat: 37.7574,
    lng: -122.3882,
    area: "Dogpatch",
    hours: "6:00–22:00",
    rating: 4.7,
    tags: ["Climbing", "Yoga"],
  },
  {
    id: "gym-f45",
    name: "F45 Training Mission",
    kind: "gym",
    lat: 37.7609,
    lng: -122.4194,
    area: "Mission",
    hours: "5:15–19:30",
    rating: 4.5,
    tags: ["Circuit", "Team"],
  },
  {
    id: "gym-ymca",
    name: "YMCA Embarcadero",
    kind: "gym",
    lat: 37.7942,
    lng: -122.3961,
    area: "Embarcadero",
    hours: "5:30–21:00",
    rating: 4.3,
    tags: ["Pool", "Basketball"],
  },
  {
    id: "store-whole-4th",
    name: "Whole Foods 4th St",
    kind: "grocery",
    lat: 37.7816,
    lng: -122.3998,
    area: "SOMA",
    hours: "8:00–22:00",
    rating: 4.4,
    tags: ["Organic", "Hot bar"],
    inventory: [
      "chicken",
      "salmon",
      "yogurt",
      "spinach",
      "berries",
      "eggs",
      "oats",
      "rice",
      "broccoli",
      "avocado",
      "tofu",
      "quinoa",
      "whey",
      "olive-oil",
      "kefir",
      "blueberries",
      "almonds",
      "sweet-potato",
    ],
  },
  {
    id: "store-tj",
    name: "Trader Joe's 9th St",
    kind: "grocery",
    lat: 37.7708,
    lng: -122.4079,
    area: "SoMa West",
    hours: "8:00–21:00",
    rating: 4.5,
    tags: ["Value", "Frozen"],
    inventory: [
      "chicken",
      "eggs",
      "oats",
      "rice",
      "spinach",
      "berries",
      "yogurt",
      "tofu",
      "avocado",
      "broccoli",
      "sweet-potato",
      "olive-oil",
      "almonds",
      "lentils",
    ],
  },
  {
    id: "store-rainbow",
    name: "Rainbow Grocery",
    kind: "grocery",
    lat: 37.7692,
    lng: -122.4199,
    area: "Mission",
    hours: "9:00–20:00",
    rating: 4.6,
    tags: ["Bulk", "Plant"],
    inventory: [
      "tofu",
      "lentils",
      "quinoa",
      "oats",
      "spinach",
      "berries",
      "almonds",
      "olive-oil",
      "kefir",
      "avocado",
      "broccoli",
      "sweet-potato",
    ],
  },
  {
    id: "store-safeway",
    name: "Safeway Marina",
    kind: "grocery",
    lat: 37.8004,
    lng: -122.4371,
    area: "Marina",
    hours: "6:00–23:00",
    rating: 4.1,
    tags: ["Late", "Pharmacy"],
    inventory: [
      "chicken",
      "eggs",
      "yogurt",
      "rice",
      "oats",
      "spinach",
      "broccoli",
      "salmon",
      "berries",
      "olive-oil",
      "sweet-potato",
      "whey",
    ],
  },
  {
    id: "store-mission",
    name: "Mission Community Market",
    kind: "grocery",
    lat: 37.7594,
    lng: -122.4188,
    area: "Mission",
    hours: "Thu 16:00–20:00",
    rating: 4.8,
    tags: ["Farmers", "Produce"],
    inventory: [
      "spinach",
      "berries",
      "avocado",
      "broccoli",
      "sweet-potato",
      "eggs",
      "blueberries",
    ],
  },
  {
    id: "store-haight",
    name: "Haight Street Market",
    kind: "grocery",
    lat: 37.7701,
    lng: -122.4469,
    area: "Haight",
    hours: "8:00–22:00",
    rating: 4.3,
    tags: ["Neighborhood"],
    inventory: [
      "eggs",
      "yogurt",
      "oats",
      "spinach",
      "chicken",
      "rice",
      "avocado",
      "berries",
      "olive-oil",
    ],
  },
];

export const INGREDIENTS: Ingredient[] = [
  { id: "chicken", name: "Chicken breast", aisle: "Meat", kcal100: 165, protein100: 31, price: 7.5, stores: ["store-whole-4th", "store-tj", "store-safeway", "store-haight"], goals: ["cut", "recomp", "bulk"] },
  { id: "salmon", name: "Atlantic salmon", aisle: "Seafood", kcal100: 208, protein100: 20, price: 14, stores: ["store-whole-4th", "store-safeway"], goals: ["cut", "recomp", "longevity"] },
  { id: "eggs", name: "Pasture eggs (12)", aisle: "Dairy", kcal100: 143, protein100: 13, price: 5.5, stores: ["store-whole-4th", "store-tj", "store-safeway", "store-haight", "store-mission"], goals: ["cut", "recomp", "bulk", "endurance", "longevity"] },
  { id: "yogurt", name: "Greek yogurt 0%", aisle: "Dairy", kcal100: 59, protein100: 10, price: 6, stores: ["store-whole-4th", "store-tj", "store-safeway", "store-haight"], goals: ["cut", "recomp", "bulk"] },
  { id: "kefir", name: "Plain kefir", aisle: "Dairy", kcal100: 41, protein100: 4, price: 4.5, stores: ["store-whole-4th", "store-rainbow"], goals: ["longevity", "recomp"] },
  { id: "spinach", name: "Baby spinach", aisle: "Produce", kcal100: 23, protein100: 3, price: 3.5, stores: ["store-whole-4th", "store-tj", "store-rainbow", "store-safeway", "store-mission", "store-haight"], goals: ["cut", "recomp", "longevity"] },
  { id: "broccoli", name: "Broccoli crowns", aisle: "Produce", kcal100: 34, protein100: 3, price: 3, stores: ["store-whole-4th", "store-tj", "store-rainbow", "store-safeway"], goals: ["cut", "recomp", "longevity"] },
  { id: "berries", name: "Mixed berries", aisle: "Produce", kcal100: 57, protein100: 1, price: 6.5, stores: ["store-whole-4th", "store-tj", "store-rainbow", "store-safeway", "store-mission", "store-haight"], goals: ["cut", "endurance", "longevity"] },
  { id: "blueberries", name: "Blueberries", aisle: "Produce", kcal100: 57, protein100: 1, price: 5.5, stores: ["store-whole-4th", "store-mission"], goals: ["longevity", "endurance"] },
  { id: "avocado", name: "Hass avocado", aisle: "Produce", kcal100: 160, protein100: 2, price: 2.5, stores: ["store-whole-4th", "store-tj", "store-rainbow", "store-mission", "store-haight"], goals: ["recomp", "bulk", "longevity"] },
  { id: "sweet-potato", name: "Sweet potatoes", aisle: "Produce", kcal100: 86, protein100: 2, price: 2, stores: ["store-whole-4th", "store-tj", "store-rainbow", "store-safeway", "store-mission"], goals: ["endurance", "bulk", "recomp"] },
  { id: "oats", name: "Rolled oats", aisle: "Dry", kcal100: 389, protein100: 17, price: 4, stores: ["store-whole-4th", "store-tj", "store-rainbow", "store-safeway", "store-haight"], goals: ["endurance", "bulk", "recomp", "cut"] },
  { id: "rice", name: "Jasmine rice", aisle: "Dry", kcal100: 130, protein100: 2.7, price: 3, stores: ["store-whole-4th", "store-tj", "store-safeway", "store-haight"], goals: ["bulk", "endurance", "recomp"] },
  { id: "quinoa", name: "Tri-color quinoa", aisle: "Dry", kcal100: 120, protein100: 4, price: 6, stores: ["store-whole-4th", "store-rainbow"], goals: ["longevity", "recomp"] },
  { id: "lentils", name: "French lentils", aisle: "Dry", kcal100: 116, protein100: 9, price: 3.5, stores: ["store-tj", "store-rainbow"], goals: ["longevity", "cut"] },
  { id: "tofu", name: "Firm tofu", aisle: "Plant", kcal100: 76, protein100: 8, price: 3, stores: ["store-whole-4th", "store-tj", "store-rainbow"], goals: ["cut", "longevity", "recomp"] },
  { id: "whey", name: "Whey isolate", aisle: "Aisle", kcal100: 370, protein100: 80, price: 28, stores: ["store-whole-4th", "store-safeway"], goals: ["cut", "recomp", "bulk"] },
  { id: "olive-oil", name: "Extra-virgin olive oil", aisle: "Aisle", kcal100: 884, protein100: 0, price: 12, stores: ["store-whole-4th", "store-tj", "store-rainbow", "store-safeway", "store-haight"], goals: ["longevity", "recomp", "bulk"] },
  { id: "almonds", name: "Raw almonds", aisle: "Aisle", kcal100: 579, protein100: 21, price: 8, stores: ["store-whole-4th", "store-tj", "store-rainbow"], goals: ["longevity", "bulk", "endurance"] },
];

export const RECIPES: Recipe[] = [
  {
    id: "miso-salmon",
    name: "Miso salmon, rice, greens",
    minutes: 25,
    kcal: 620,
    protein: 48,
    ingredients: ["salmon", "rice", "spinach", "broccoli", "olive-oil"],
    steps: [
      "Heat oven to 400°F. Paint salmon with a thin miso-honey glaze.",
      "Roast 10–12 minutes while rice steams.",
      "Sauté spinach and broccoli in olive oil, plate, squeeze lemon.",
    ],
    goals: ["cut", "recomp", "longevity"],
    photo: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "yogurt-bowl",
    name: "High-protein yogurt bowl",
    minutes: 8,
    kcal: 410,
    protein: 42,
    ingredients: ["yogurt", "berries", "oats", "almonds", "whey"],
    steps: [
      "Stir whey into yogurt until smooth.",
      "Top with oats, berries, crushed almonds.",
    ],
    goals: ["cut", "recomp", "bulk"],
    photo: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "chicken-rice",
    name: "Lemon chicken and rice",
    minutes: 30,
    kcal: 580,
    protein: 52,
    ingredients: ["chicken", "rice", "broccoli", "olive-oil"],
    steps: [
      "Salt chicken, sear 3 minutes a side in olive oil.",
      "Finish in pan with lemon and garlic. Steam broccoli.",
      "Serve over rice with pan juices.",
    ],
    goals: ["cut", "recomp", "bulk"],
    photo: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "tofu-quinoa",
    name: "Crispy tofu quinoa bowl",
    minutes: 28,
    kcal: 540,
    protein: 32,
    ingredients: ["tofu", "quinoa", "spinach", "avocado", "olive-oil"],
    steps: [
      "Press tofu, cube, roast at 425°F until edges bronze.",
      "Fluff quinoa, fold spinach through residual heat.",
      "Sliced avocado, chili, lime.",
    ],
    goals: ["longevity", "cut", "recomp"],
    photo: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "oat-engine",
    name: "Endurance oat engine",
    minutes: 12,
    kcal: 680,
    protein: 28,
    ingredients: ["oats", "kefir", "blueberries", "almonds", "sweet-potato"],
    steps: [
      "Overnight oats in kefir.",
      "Warm a small roasted sweet potato, mash through.",
      "Blueberries and almonds on top. Salt.",
    ],
    goals: ["endurance", "longevity", "bulk"],
    photo: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "egg-hash",
    name: "Savory egg and sweet potato hash",
    minutes: 20,
    kcal: 490,
    protein: 28,
    ingredients: ["eggs", "sweet-potato", "spinach", "olive-oil"],
    steps: [
      "Cube sweet potato, pan-roast until tender.",
      "Wilt spinach, make wells, crack eggs, lid 3 minutes.",
    ],
    goals: ["recomp", "longevity", "cut"],
    photo: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "lentil-bowl",
    name: "Warm lentil and greens bowl",
    minutes: 35,
    kcal: 470,
    protein: 26,
    ingredients: ["lentils", "spinach", "olive-oil", "avocado"],
    steps: [
      "Simmer lentils in salted water 22 minutes.",
      "Dress with olive oil, lemon, chili. Fold spinach. Avocado.",
    ],
    goals: ["longevity", "cut"],
    photo: "https://images.unsplash.com/photo-1511690655826-5668a0397c16?auto=format&fit=crop&w=1200&q=80",
  },
];

export const FOODS: Food[] = [
  {
    id: "salmon-bowl",
    name: "Miso salmon bowl",
    kcal: 620,
    protein: 48,
    carbs: 52,
    fat: 22,
    keywords: ["salmon", "fish", "miso", "bowl"],
    meal: ["lunch", "dinner"],
    photo: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80",
    ingredients: ["salmon", "rice", "spinach"],
  },
  {
    id: "yogurt",
    name: "Berry yogurt bowl",
    kcal: 410,
    protein: 42,
    carbs: 38,
    fat: 9,
    keywords: ["yogurt", "berry", "breakfast", "bowl"],
    meal: ["breakfast", "snack"],
    photo: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",
    ingredients: ["yogurt", "berries", "oats"],
  },
  {
    id: "chicken-plate",
    name: "Lemon chicken, rice, broccoli",
    kcal: 580,
    protein: 52,
    carbs: 48,
    fat: 16,
    keywords: ["chicken", "rice", "broccoli", "lunch"],
    meal: ["lunch", "dinner"],
    photo: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80",
    ingredients: ["chicken", "rice", "broccoli"],
  },
  {
    id: "oats",
    name: "Overnight oats",
    kcal: 480,
    protein: 24,
    carbs: 62,
    fat: 14,
    keywords: ["oat", "oatmeal", "breakfast"],
    meal: ["breakfast"],
    photo: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80",
    ingredients: ["oats", "kefir", "blueberries"],
  },
  {
    id: "salad",
    name: "Chicken avocado salad",
    kcal: 430,
    protein: 38,
    carbs: 14,
    fat: 24,
    keywords: ["salad", "avocado", "greens"],
    meal: ["lunch", "dinner"],
    photo: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    ingredients: ["chicken", "avocado", "spinach"],
  },
  {
    id: "eggs-toast",
    name: "Eggs and sourdough",
    kcal: 390,
    protein: 22,
    carbs: 32,
    fat: 18,
    keywords: ["egg", "toast", "breakfast"],
    meal: ["breakfast"],
    photo: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    ingredients: ["eggs", "spinach"],
  },
  {
    id: "tofu-bowl",
    name: "Crispy tofu bowl",
    kcal: 540,
    protein: 32,
    carbs: 48,
    fat: 22,
    keywords: ["tofu", "quinoa", "vegan"],
    meal: ["lunch", "dinner"],
    photo: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    ingredients: ["tofu", "quinoa", "avocado"],
  },
  {
    id: "espresso-bar",
    name: "Protein bar + espresso",
    kcal: 280,
    protein: 20,
    carbs: 24,
    fat: 10,
    keywords: ["bar", "coffee", "snack", "protein"],
    meal: ["snack"],
    photo: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    ingredients: ["whey"],
  },
];

export const FRIENDS: Friend[] = [
  { id: "maya", name: "Maya Chen", handle: "maya.splits", city: "SF", recovery: 92, strain: 12.4, streak: 61, pace: "Hyrox prep", online: true },
  { id: "jordan", name: "Jordan Blake", handle: "j.blake", city: "Oakland", recovery: 64, strain: 16.8, streak: 14, pace: "Cut, 8 weeks", online: true },
  { id: "sam", name: "Sam Okonkwo", handle: "sam.ok", city: "SF", recovery: 81, strain: 9.1, streak: 40, pace: "Zone 2 block", online: false },
  { id: "riley", name: "Riley Park", handle: "riley.p", city: "Berkeley", recovery: 77, strain: 14.2, streak: 22, pace: "First 70.3", online: true },
  { id: "chris", name: "Chris Nguyen", handle: "cnguyen", city: "SF", recovery: 88, strain: 7.6, streak: 103, pace: "Sleep-first", online: false },
];

export const SEED_POSTS: CommunityPost[] = [
  {
    id: "p1",
    authorId: "maya",
    author: "Maya Chen",
    handle: "maya.splits",
    text: "6am Hyrox sim. Burpee broad jumps still humble me. Who's in for Saturday hills?",
    photo: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=80",
    at: hoursAgo(3),
    likes: 24,
    liked: false,
    comments: [
      { id: "c1", author: "Riley Park", text: "I'm in. 8:30 at the steps." },
      { id: "c2", author: "You", text: "If recovery holds, yes." },
    ],
    stats: { recovery: 92, strain: 14.1, workout: "Hyrox sim · 54 min" },
  },
  {
    id: "p2",
    authorId: "sam",
    author: "Sam Okonkwo",
    handle: "sam.ok",
    text: "90 minutes conversational on the Great Highway. HR capped at 142. This is the work.",
    photo: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=80",
    at: hoursAgo(8),
    likes: 18,
    liked: true,
    comments: [{ id: "c3", author: "Chris Nguyen", text: "Boring on purpose. Love it." }],
    stats: { strain: 9.1, workout: "Z2 run · 90 min" },
  },
  {
    id: "p3",
    authorId: "jordan",
    author: "Jordan Blake",
    handle: "j.blake",
    text: "Logged the salmon bowl with a photo. AI was 20 kcal off. I'll take it.",
    photo: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1400&q=80",
    at: hoursAgo(20),
    likes: 11,
    liked: false,
    comments: [],
    stats: { strain: 16.8 },
  },
];

export const STRAVA_ACTIVITIES = [
  {
    id: "st1",
    name: "Embarcadero tempo",
    type: "Run",
    km: 10.2,
    elevation: 48,
    moving: "48:12",
    kudos: 34,
    when: "Yesterday · 6:14 AM",
  },
  {
    id: "st2",
    name: "Twin Peaks spin",
    type: "Ride",
    km: 34.8,
    elevation: 612,
    moving: "1:32:04",
    kudos: 21,
    when: "Wed · 5:40 PM",
  },
  {
    id: "st3",
    name: "Easy Golden Gate",
    type: "Run",
    km: 8.1,
    elevation: 92,
    moving: "46:50",
    kudos: 16,
    when: "Tue · 7:02 AM",
  },
];

export const USER = {
  id: "me",
  name: "Alex Rivera",
  handle: "alex.pact",
  city: "San Francisco",
  streak: 47,
};

export const YOU_ARE_HERE = { lat: 37.7749, lng: -122.4194 };

function hoursAgo(h: number) {
  return new Date(Date.parse("2026-09-12T18:00:00.000Z") - h * 3600_000).toISOString();
}

export function goalById(id: Goal["id"]) {
  return GOALS.find((g) => g.id === id) ?? GOALS[0];
}

export function analyzePhoto(fileName: string, hour: number): Food {
  const lower = fileName.toLowerCase();
  const hit = FOODS.find((f) => f.keywords.some((k) => lower.includes(k)));
  if (hit) return hit;
  if (hour < 11) return FOODS.find((f) => f.id === "yogurt") ?? FOODS[0];
  if (hour < 16) return FOODS.find((f) => f.id === "salad") ?? FOODS[0];
  if (hour < 21) return FOODS.find((f) => f.id === "salmon-bowl") ?? FOODS[0];
  return FOODS.find((f) => f.id === "espresso-bar") ?? FOODS[0];
}

export function recipesFor(goal: Goal["id"], selected: string[]) {
  const scored = RECIPES.filter((r) => r.goals.includes(goal)).map((r) => {
    const overlap = r.ingredients.filter((i) => selected.includes(i)).length;
    return { recipe: r, overlap };
  });
  scored.sort((a, b) => b.overlap - a.overlap || a.recipe.minutes - b.recipe.minutes);
  return scored;
}

export function haversineKm(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number },
) {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((a.lat * Math.PI) / 180) *
      Math.cos((b.lat * Math.PI) / 180) *
      Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
