import { labelsFor, type MuscleId } from "./muscles";
import type { Workout, WorkoutPattern } from "./types";

function lift(
  row: Omit<Workout, "kind" | "category" | "muscles"> & {
    primary: MuscleId[];
    secondary?: MuscleId[];
    category?: string;
    pattern: WorkoutPattern;
  },
): Workout {
  return {
    ...row,
    kind: "lift",
    category: row.category ?? "Strength",
    muscles: labelsFor(row.primary, row.secondary),
  };
}

/** Single-lift form films — how to run the pattern, not a follow-along class. */
export const LIFT_VIDEOS: Workout[] = [
  lift({
    id: "lift-squat",
    title: "Barbell back squat",
    trainer: "ScottHermanFitness",
    youtubeId: "1oed-UmAxFs",
    minutes: 10,
    level: "Beginner",
    kcal: 40,
    equipment: ["Barbell", "Rack"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    pattern: "squat",
    prescription: "4 × 5–8",
    rest: "2–3 min",
    progression: "Add 2.5 kg when the top of the range is a 2-RIR set.",
    alternatives: ["lift-goblet", "lift-front-squat", "lift-hack", "lift-legpress"],
    cue: "Drive the floor. Knees track toes. Brace before you unrack.",
  }),
  lift({
    id: "lift-front-squat",
    title: "Front squat",
    trainer: "ScottHermanFitness",
    youtubeId: "tlfahNdNPPI",
    minutes: 8,
    level: "Intermediate",
    kcal: 40,
    equipment: ["Barbell", "Rack"],
    primary: ["quads", "abs"],
    secondary: ["glutes", "front-delt"],
    pattern: "squat",
    prescription: "4 × 5–8",
    rest: "2–3 min",
    alternatives: ["lift-goblet", "lift-squat", "lift-hack"],
    cue: "Elbows up. Sit between the hips. If the bar rolls, the torso is folding.",
  }),
  lift({
    id: "lift-goblet",
    title: "Goblet squat",
    trainer: "ScottHermanFitness",
    youtubeId: "MeIiIdhvXT4",
    minutes: 5,
    level: "Beginner",
    kcal: 28,
    equipment: ["Dumbbells"],
    primary: ["quads", "glutes"],
    secondary: ["abs"],
    pattern: "squat",
    prescription: "3 × 10–15",
    rest: "90s",
    alternatives: ["lift-squat", "lift-legpress"],
    cue: "Bell at the sternum. Elbows inside the knees. Heels stay heavy.",
  }),
  lift({
    id: "lift-hack",
    title: "Smith / hack squat",
    trainer: "ScottHermanFitness",
    youtubeId: "LfEhHboTcow",
    minutes: 5,
    level: "Intermediate",
    kcal: 35,
    equipment: ["Machine"],
    primary: ["quads"],
    secondary: ["glutes", "hamstrings"],
    pattern: "squat",
    prescription: "3 × 8–12",
    rest: "2 min",
    alternatives: ["lift-legpress", "lift-squat"],
    cue: "Low back glued to the pad. Don't chase depth that tucks the pelvis.",
  }),
  lift({
    id: "lift-legpress",
    title: "Seated leg press",
    trainer: "ScottHermanFitness",
    youtubeId: "IZxyjW7MPJQ",
    minutes: 4,
    level: "Beginner",
    kcal: 30,
    equipment: ["Machine"],
    primary: ["quads"],
    secondary: ["glutes", "hamstrings"],
    pattern: "squat",
    prescription: "3 × 10–15",
    rest: "90s",
    alternatives: ["lift-hack", "lift-squat"],
    cue: "Feet mid-platform. Don't lock out angry. Keep the low back glued to the pad.",
  }),
  lift({
    id: "lift-leg-ext",
    title: "Leg extension",
    trainer: "ScottHermanFitness",
    youtubeId: "YyvSfVjQeL0",
    minutes: 4,
    level: "Beginner",
    kcal: 20,
    equipment: ["Machine"],
    primary: ["quads"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60–90s",
    alternatives: ["lift-hack"],
    cue: "Control the eccentric. Squeeze at lockout. Don't throw the stack.",
  }),
  lift({
    id: "lift-bss",
    title: "Bulgarian split squat",
    trainer: "ScottHermanFitness",
    youtubeId: "2C-uNgKwPLE",
    minutes: 4,
    level: "Intermediate",
    kcal: 30,
    equipment: ["Dumbbells", "Bench"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    pattern: "lunge",
    prescription: "3 × 8–12 / leg",
    rest: "90s",
    alternatives: ["lift-lunge", "lift-reverse-lunge", "lift-stepup"],
    cue: "Front heel heavy. Torso tall. Back foot is a kickstand, not the worker.",
  }),
  lift({
    id: "lift-lunge",
    title: "Walking lunge",
    trainer: "ScottHermanFitness",
    youtubeId: "D7KaRcUTQeE",
    minutes: 5,
    level: "Beginner",
    kcal: 32,
    equipment: ["Dumbbells"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    pattern: "lunge",
    prescription: "3 × 10 / leg",
    rest: "90s",
    alternatives: ["lift-reverse-lunge", "lift-bss"],
    cue: "Knee tracks the mid-foot. Shorten the step if the front heel pops.",
  }),
  lift({
    id: "lift-reverse-lunge",
    title: "Reverse lunge",
    trainer: "ScottHermanFitness",
    youtubeId: "sjlsISvHyZs",
    minutes: 4,
    level: "Beginner",
    kcal: 28,
    equipment: ["Dumbbells"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    pattern: "lunge",
    prescription: "3 × 8–12 / leg",
    rest: "90s",
    alternatives: ["lift-lunge", "lift-bss"],
    cue: "Step back, not down. Front shin stays fairly vertical.",
  }),
  lift({
    id: "lift-stepup",
    title: "Dumbbell step-up",
    trainer: "Bobby Maximus",
    youtubeId: "9ZknEYboBOQ",
    minutes: 4,
    level: "Beginner",
    kcal: 26,
    equipment: ["Dumbbells", "Box"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    pattern: "lunge",
    prescription: "3 × 8–12 / leg",
    rest: "90s",
    alternatives: ["lift-bss", "lift-lunge"],
    cue: "Drive through the working heel. Don't push off the trailing toe.",
  }),
  lift({
    id: "lift-pistol",
    title: "Pistol squat progression",
    trainer: "CrossFit",
    youtubeId: "q11UwY5gd0A",
    minutes: 9,
    level: "Advanced",
    kcal: 35,
    equipment: ["None"],
    primary: ["quads", "glutes"],
    secondary: ["abs", "hamstrings"],
    pattern: "squat",
    prescription: "3 × 5–8 / leg",
    rest: "2 min",
    alternatives: ["lift-bss", "lift-goblet"],
    cue: "Own the eccentric. Counterbalance with the arms. Depth without the lumbar tuck.",
  }),
  lift({
    id: "lift-deadlift",
    title: "Conventional deadlift",
    trainer: "Jeff Nippard",
    youtubeId: "ZaTM37cfiDs",
    minutes: 8,
    level: "Intermediate",
    kcal: 50,
    equipment: ["Barbell"],
    primary: ["hamstrings", "glutes", "traps"],
    secondary: ["lats", "quads", "abs"],
    pattern: "hinge",
    prescription: "4 × 3–6",
    rest: "3 min",
    alternatives: ["lift-sumo", "lift-trapbar", "lift-rdl"],
    cue: "Bar over mid-foot. Pull the slack. Hips and shoulders rise together.",
  }),
  lift({
    id: "lift-sumo",
    title: "Sumo deadlift",
    trainer: "Jeff Nippard",
    youtubeId: "XsrD5y8EIKU",
    minutes: 8,
    level: "Intermediate",
    kcal: 48,
    equipment: ["Barbell"],
    primary: ["glutes", "quads", "hamstrings"],
    secondary: ["traps", "abs"],
    pattern: "hinge",
    prescription: "4 × 3–6",
    rest: "3 min",
    alternatives: ["lift-deadlift", "lift-trapbar"],
    cue: "Hips close to the bar. Push the floor apart. Don't turn it into a good morning.",
  }),
  lift({
    id: "lift-trapbar",
    title: "Trap-bar deadlift",
    trainer: "Alan Thrall",
    youtubeId: "TU2xZ7s4jus",
    minutes: 6,
    level: "Beginner",
    kcal: 45,
    equipment: ["Trap bar"],
    primary: ["quads", "glutes", "hamstrings"],
    secondary: ["traps", "abs"],
    pattern: "hinge",
    prescription: "4 × 5–8",
    rest: "2–3 min",
    alternatives: ["lift-deadlift", "lift-squat"],
    cue: "High handles if you're learning. Sit between the hips. Neutral spine.",
  }),
  lift({
    id: "lift-rdl",
    title: "Dumbbell Romanian deadlift",
    trainer: "ScottHermanFitness",
    youtubeId: "FQKfr1YDhEk",
    minutes: 4,
    level: "Beginner",
    kcal: 30,
    equipment: ["Dumbbells"],
    primary: ["hamstrings", "glutes"],
    secondary: ["traps", "abs"],
    pattern: "hinge",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-bb-rdl", "lift-good-morning"],
    cue: "Push the hips back. Soft knees. Feel the hamstring before you stand.",
  }),
  lift({
    id: "lift-bb-rdl",
    title: "Barbell Romanian deadlift",
    trainer: "ScottHermanFitness",
    youtubeId: "jEy_czb3RKA",
    minutes: 6,
    level: "Intermediate",
    kcal: 38,
    equipment: ["Barbell"],
    primary: ["hamstrings", "glutes"],
    secondary: ["traps", "lats"],
    pattern: "hinge",
    prescription: "3 × 6–10",
    rest: "2 min",
    alternatives: ["lift-rdl", "lift-deadlift", "lift-good-morning"],
    cue: "Bar stays on the legs. Hinge, don't squat. Stop when the back wants to round.",
  }),
  lift({
    id: "lift-good-morning",
    title: "Good morning",
    trainer: "ScottHermanFitness",
    youtubeId: "5Xj6XUa77qc",
    minutes: 5,
    level: "Intermediate",
    kcal: 28,
    equipment: ["Barbell"],
    primary: ["hamstrings", "glutes"],
    secondary: ["abs"],
    pattern: "hinge",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-bb-rdl", "lift-rdl"],
    cue: "Soft knees. Hips back. This is a hinge with a shelf, not a bow.",
  }),
  lift({
    id: "lift-nordic",
    title: "Nordic hamstring curl",
    trainer: "ATHLEAN-X",
    youtubeId: "vynsCfHZ69A",
    minutes: 8,
    level: "Advanced",
    kcal: 30,
    equipment: ["None"],
    primary: ["hamstrings"],
    secondary: ["glutes", "calves"],
    pattern: "isolation",
    prescription: "3 × 4–8",
    rest: "2 min",
    alternatives: ["lift-leg-curl", "lift-bb-rdl"],
    cue: "Slow the fall. Hands catch only when the hamstrings tap out.",
  }),
  lift({
    id: "lift-leg-curl",
    title: "Lying hamstring curl",
    trainer: "ScottHermanFitness",
    youtubeId: "1Tq3QdYUuHs",
    minutes: 4,
    level: "Beginner",
    kcal: 20,
    equipment: ["Machine"],
    primary: ["hamstrings"],
    secondary: ["calves"],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60–90s",
    alternatives: ["lift-seated-curl", "lift-nordic"],
    cue: "Hips stay on the pad. Full squeeze. Don't bounce the stack.",
  }),
  lift({
    id: "lift-seated-curl",
    title: "Seated hamstring curl",
    trainer: "ScottHermanFitness",
    youtubeId: "ELOCsoDSmrg",
    minutes: 4,
    level: "Beginner",
    kcal: 20,
    equipment: ["Machine"],
    primary: ["hamstrings"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60–90s",
    alternatives: ["lift-leg-curl"],
    cue: "Lock the lap pad. Curl without the hips scooting forward.",
  }),
  lift({
    id: "lift-hip-thrust",
    title: "Hip thrust",
    trainer: "Jeff Nippard",
    youtubeId: "xDmFkJxPzeM",
    minutes: 10,
    level: "Beginner",
    kcal: 40,
    equipment: ["Barbell", "Bench"],
    primary: ["glutes"],
    secondary: ["hamstrings", "quads"],
    pattern: "hinge",
    prescription: "4 × 8–12",
    rest: "2 min",
    alternatives: ["lift-glute-bridge", "lift-cable-kickback"],
    cue: "Ribs down at lockout. Pause. Don't chase lumbar extension.",
  }),
  lift({
    id: "lift-glute-bridge",
    title: "Glute bridge",
    trainer: "PostureFlow",
    youtubeId: "Q_Bpj91Yiis",
    minutes: 4,
    level: "Beginner",
    kcal: 18,
    equipment: ["None"],
    primary: ["glutes"],
    secondary: ["hamstrings"],
    pattern: "hinge",
    prescription: "3 × 12–20",
    rest: "60s",
    alternatives: ["lift-hip-thrust"],
    cue: "Posterior tilt. Squeeze at the top. Don't arch into the neck.",
  }),
  lift({
    id: "lift-cable-kickback",
    title: "Cable glute kickback",
    trainer: "PureGym",
    youtubeId: "SqO-VUEak2M",
    minutes: 4,
    level: "Beginner",
    kcal: 18,
    equipment: ["Cable"],
    primary: ["glutes"],
    secondary: ["hamstrings"],
    pattern: "isolation",
    prescription: "3 × 12–15 / leg",
    rest: "60s",
    alternatives: ["lift-hip-thrust"],
    cue: "Square the hips. Kick back, not up into a backbend.",
  }),
  lift({
    id: "lift-hip-abductor",
    title: "Side-lying hip abduction",
    trainer: "3v",
    youtubeId: "jgh6sGwtTwk",
    minutes: 3,
    level: "Beginner",
    kcal: 16,
    equipment: ["None"],
    primary: ["glutes"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 12–20",
    rest: "60s",
    alternatives: ["lift-adductor", "lift-cable-kickback"],
    cue: "Top hip stacked. Lift from the side of the glute, not a swinging kick.",
  }),
  lift({
    id: "lift-calf",
    title: "Standing calf raise",
    trainer: "LIVESTRONG",
    youtubeId: "gwLzBJYoWlI",
    minutes: 3,
    level: "Beginner",
    kcal: 15,
    equipment: ["None"],
    primary: ["calves"],
    secondary: ["soleus"],
    pattern: "isolation",
    prescription: "4 × 10–15",
    rest: "60s",
    alternatives: ["lift-seated-calf"],
    cue: "Full stretch at the bottom. Pause at the top. Don't bounce.",
  }),
  lift({
    id: "lift-seated-calf",
    title: "Seated calf raise",
    trainer: "Hinge Health",
    youtubeId: "BxfKOyI8sUg",
    minutes: 3,
    level: "Beginner",
    kcal: 15,
    equipment: ["Machine"],
    primary: ["soleus", "calves"],
    secondary: [],
    pattern: "isolation",
    prescription: "4 × 10–15",
    rest: "60s",
    alternatives: ["lift-calf"],
    cue: "This hits soleus. Slow stretch, hard squeeze, no bounce.",
  }),
  lift({
    id: "lift-bench",
    title: "Barbell bench press",
    trainer: "ScottHermanFitness",
    youtubeId: "rT7DgCr-3pg",
    minutes: 6,
    level: "Beginner",
    kcal: 35,
    equipment: ["Barbell", "Bench"],
    primary: ["chest"],
    secondary: ["triceps", "front-delt"],
    pattern: "horizontal-push",
    prescription: "4 × 5–8",
    rest: "2–3 min",
    alternatives: ["lift-db-press", "lift-incline", "lift-pushup", "lift-floor-press"],
    cue: "Touch the chest, don't bounce it. Elbows ~45°. Feet stay planted.",
  }),
  lift({
    id: "lift-incline-bb",
    title: "Incline barbell press",
    trainer: "ScottHermanFitness",
    youtubeId: "DbFgADa2PL8",
    minutes: 5,
    level: "Intermediate",
    kcal: 32,
    equipment: ["Barbell", "Bench"],
    primary: ["chest", "front-delt"],
    secondary: ["triceps"],
    pattern: "horizontal-push",
    prescription: "4 × 6–10",
    rest: "2 min",
    alternatives: ["lift-incline", "lift-bench"],
    cue: "30–45° is plenty. Lower to the upper chest, not the throat.",
  }),
  lift({
    id: "lift-incline",
    title: "Incline dumbbell press",
    trainer: "ScottHermanFitness",
    youtubeId: "8iPEnn-ltC8",
    minutes: 4,
    level: "Beginner",
    kcal: 30,
    equipment: ["Dumbbells", "Bench"],
    primary: ["chest", "front-delt"],
    secondary: ["triceps"],
    pattern: "horizontal-push",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-incline-bb", "lift-bench"],
    cue: "30–45° bench. Lower to the upper chest, not the face.",
  }),
  lift({
    id: "lift-decline",
    title: "Decline bench press",
    trainer: "ScottHermanFitness",
    youtubeId: "LfyQBUKR8SE",
    minutes: 5,
    level: "Intermediate",
    kcal: 32,
    equipment: ["Barbell", "Bench"],
    primary: ["chest"],
    secondary: ["triceps"],
    pattern: "horizontal-push",
    prescription: "3 × 6–10",
    rest: "2 min",
    alternatives: ["lift-bench", "lift-dip"],
    cue: "Shoulder blades parked. Don't let the bar drift toward the face.",
  }),
  lift({
    id: "lift-close-bench",
    title: "Close-grip bench press",
    trainer: "ScottHermanFitness",
    youtubeId: "nEF0bv2FW94",
    minutes: 5,
    level: "Intermediate",
    kcal: 30,
    equipment: ["Barbell", "Bench"],
    primary: ["triceps", "chest"],
    secondary: ["front-delt"],
    pattern: "horizontal-push",
    prescription: "3 × 6–10",
    rest: "2 min",
    alternatives: ["lift-skull", "lift-dip"],
    cue: "Hands just inside shoulder width. Elbows track, they don't flare to 90.",
  }),
  lift({
    id: "lift-floor-press",
    title: "Floor press",
    trainer: "ScottHermanFitness",
    youtubeId: "uUGDRwge4F8",
    minutes: 5,
    level: "Intermediate",
    kcal: 28,
    equipment: ["Barbell"],
    primary: ["chest", "triceps"],
    secondary: ["front-delt"],
    pattern: "horizontal-push",
    prescription: "3 × 6–10",
    rest: "2 min",
    alternatives: ["lift-bench", "lift-close-bench"],
    cue: "Pause on the floor. Press without bouncing the triceps off the ground.",
  }),
  lift({
    id: "lift-db-press",
    title: "Dumbbell shoulder press",
    trainer: "ScottHermanFitness",
    youtubeId: "qEwKCR5JCog",
    minutes: 4,
    level: "Beginner",
    kcal: 25,
    equipment: ["Dumbbells"],
    primary: ["front-delt"],
    secondary: ["triceps"],
    pattern: "vertical-push",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-ohp", "lift-arnold", "lift-landmine"],
    cue: "Wrists stacked over elbows. Don't flare into a pec fly at the bottom.",
  }),
  lift({
    id: "lift-ohp",
    title: "Standing overhead press",
    trainer: "ScottHermanFitness",
    youtubeId: "2yjwXTZQDDI",
    minutes: 5,
    level: "Intermediate",
    kcal: 30,
    equipment: ["Barbell"],
    primary: ["front-delt"],
    secondary: ["triceps", "traps", "abs"],
    pattern: "vertical-push",
    prescription: "4 × 5–8",
    rest: "2–3 min",
    alternatives: ["lift-db-press", "lift-landmine", "lift-pike-push"],
    cue: "Glutes on. Head through at the top. Don't lean into a standing bench.",
  }),
  lift({
    id: "lift-arnold",
    title: "Arnold press",
    trainer: "ScottHermanFitness",
    youtubeId: "6Z15_WdXmVw",
    minutes: 4,
    level: "Intermediate",
    kcal: 24,
    equipment: ["Dumbbells"],
    primary: ["front-delt"],
    secondary: ["triceps"],
    pattern: "vertical-push",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-db-press"],
    cue: "Rotate as you press. Don't let the bells crash together at the top.",
  }),
  lift({
    id: "lift-landmine",
    title: "Landmine press",
    trainer: "mountaindog1",
    youtubeId: "qFXojXa-RCU",
    minutes: 5,
    level: "Beginner",
    kcal: 24,
    equipment: ["Barbell"],
    primary: ["front-delt", "chest"],
    secondary: ["triceps", "abs"],
    pattern: "vertical-push",
    prescription: "3 × 8–12 / side",
    rest: "90s",
    alternatives: ["lift-ohp", "lift-db-press"],
    cue: "Stagger the stance. Press up and in. Ribs stay stacked.",
  }),
  lift({
    id: "lift-lateral",
    title: "Dumbbell lateral raise",
    trainer: "ScottHermanFitness",
    youtubeId: "3VcKaXpzqRo",
    minutes: 4,
    level: "Beginner",
    kcal: 20,
    equipment: ["Dumbbells"],
    primary: ["front-delt"],
    secondary: ["traps"],
    pattern: "isolation",
    prescription: "3 × 12–20",
    rest: "60s",
    alternatives: ["lift-facepull"],
    cue: "Lead with the elbow. Pinkies slightly up. Stop at shoulder height.",
  }),
  lift({
    id: "lift-front-raise",
    title: "Dumbbell front raise",
    trainer: "ScottHermanFitness",
    youtubeId: "sOcYlBI85hc",
    minutes: 3,
    level: "Beginner",
    kcal: 16,
    equipment: ["Dumbbells"],
    primary: ["front-delt"],
    secondary: ["chest"],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-ohp", "lift-lateral"],
    cue: "Raise to eye height. Don't swing the hips into it.",
  }),
  lift({
    id: "lift-rear-fly",
    title: "Rear-delt fly",
    trainer: "ATHLEAN-X",
    youtubeId: "EA7u4Q_8HQ0",
    minutes: 6,
    level: "Beginner",
    kcal: 18,
    equipment: ["Dumbbells"],
    primary: ["traps"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "3 × 12–20",
    rest: "60s",
    alternatives: ["lift-facepull"],
    cue: "Hinge. Pinkies lead. Think reverse pec-deck, not a row.",
  }),
  lift({
    id: "lift-facepull",
    title: "Face pull",
    trainer: "ScottHermanFitness",
    youtubeId: "rep-qVOkqgk",
    minutes: 4,
    level: "Beginner",
    kcal: 20,
    equipment: ["Cable", "Rope"],
    primary: ["traps"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "3 × 12–20",
    rest: "60s",
    alternatives: ["lift-rear-fly"],
    cue: "Elbows higher than wrists. Pinch the shoulder blades to the face.",
  }),
  lift({
    id: "lift-shrug",
    title: "Barbell shrug",
    trainer: "ScottHermanFitness",
    youtubeId: "cJRVVxmytaM",
    minutes: 3,
    level: "Beginner",
    kcal: 18,
    equipment: ["Barbell"],
    primary: ["traps"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    cue: "Straight up, not a roll. Pause at the top. Arms stay long.",
  }),
  lift({
    id: "lift-pushup",
    title: "The perfect push-up",
    trainer: "Calisthenic Movement",
    youtubeId: "IODxDxX7oi4",
    minutes: 8,
    level: "Beginner",
    kcal: 60,
    equipment: ["None"],
    primary: ["chest", "triceps"],
    secondary: ["abs", "front-delt"],
    pattern: "horizontal-push",
    prescription: "3 × 8–20",
    rest: "90s",
    alternatives: ["lift-bench", "lift-diamond", "lift-dip"],
    cue: "Screw the floor away. Hollow the ribcage.",
  }),
  lift({
    id: "lift-diamond",
    title: "Diamond push-up",
    trainer: "Calisthenic Movement",
    youtubeId: "J0DnG1_S92I",
    minutes: 5,
    level: "Intermediate",
    kcal: 28,
    equipment: ["None"],
    primary: ["triceps", "chest"],
    secondary: ["abs"],
    pattern: "horizontal-push",
    prescription: "3 × 6–15",
    rest: "90s",
    alternatives: ["lift-pushup", "lift-close-bench"],
    cue: "Hands under the sternum. Elbows in. Don't pike the hips.",
  }),
  lift({
    id: "lift-pike-push",
    title: "Pike push-up",
    trainer: "Chris Calisthenics",
    youtubeId: "lIZ_C4VJnmc",
    minutes: 6,
    level: "Intermediate",
    kcal: 30,
    equipment: ["None"],
    primary: ["front-delt", "triceps"],
    secondary: ["abs"],
    pattern: "vertical-push",
    prescription: "3 × 6–12",
    rest: "90s",
    alternatives: ["lift-ohp", "lift-db-press"],
    cue: "Hips high. Head to the floor between the hands, not a downward dog crunch.",
  }),
  lift({
    id: "lift-dip",
    title: "Dips — chest vs triceps",
    trainer: "ScottHermanFitness",
    youtubeId: "sM6XUdt1rm4",
    minutes: 6,
    level: "Intermediate",
    kcal: 40,
    equipment: ["Dip bars"],
    primary: ["triceps", "chest"],
    secondary: ["front-delt"],
    pattern: "horizontal-push",
    prescription: "3 × 6–12",
    rest: "2 min",
    alternatives: ["lift-bench-dip", "lift-close-bench"],
    cue: "Upright = triceps. Lean + wider = chest. Stop before the shoulder complains.",
  }),
  lift({
    id: "lift-bench-dip",
    title: "Bench dip",
    trainer: "ScottHermanFitness",
    youtubeId: "0326dy_-CzM",
    minutes: 3,
    level: "Beginner",
    kcal: 18,
    equipment: ["Bench"],
    primary: ["triceps"],
    secondary: ["chest", "front-delt"],
    pattern: "isolation",
    prescription: "3 × 8–15",
    rest: "60s",
    alternatives: ["lift-dip", "lift-pushdown"],
    cue: "Shoulders down. Don't sink past a 90° elbow if the front of the shoulder talks.",
  }),
  lift({
    id: "lift-fly",
    title: "Dumbbell chest fly",
    trainer: "ScottHermanFitness",
    youtubeId: "eozdVDA78K0",
    minutes: 3,
    level: "Beginner",
    kcal: 20,
    equipment: ["Dumbbells", "Bench"],
    primary: ["chest"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60–90s",
    alternatives: ["lift-crossover"],
    cue: "Soft elbows. Hug a barrel. Stop when the pec is stretched, not the capsule.",
  }),
  lift({
    id: "lift-crossover",
    title: "Cable crossover",
    trainer: "ScottHermanFitness",
    youtubeId: "taI4XduLpTk",
    minutes: 4,
    level: "Beginner",
    kcal: 20,
    equipment: ["Cable"],
    primary: ["chest"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-fly"],
    cue: "Slight forward lean. Hands meet in front of the sternum. Don't shrug.",
  }),
  lift({
    id: "lift-row",
    title: "Bent-over barbell row",
    trainer: "Max Euceda",
    youtubeId: "FWJR5Ve8bnQ",
    minutes: 3,
    level: "Intermediate",
    kcal: 25,
    equipment: ["Barbell"],
    primary: ["lats", "traps"],
    secondary: ["biceps", "hamstrings"],
    pattern: "horizontal-pull",
    prescription: "4 × 6–10",
    rest: "2 min",
    alternatives: ["lift-pendlay", "lift-one-arm-row", "lift-cable-row"],
    cue: "Hinge, then row to the hip. Don't turn it into a shrug.",
  }),
  lift({
    id: "lift-pendlay",
    title: "Pendlay row",
    trainer: "Alan Thrall",
    youtubeId: "8CrrVQi6t4w",
    minutes: 6,
    level: "Intermediate",
    kcal: 30,
    equipment: ["Barbell"],
    primary: ["lats", "traps"],
    secondary: ["biceps"],
    pattern: "horizontal-pull",
    prescription: "4 × 5–8",
    rest: "2 min",
    alternatives: ["lift-row", "lift-tbar"],
    cue: "Dead stop on the floor. Explosive pull, controlled drop. Torso stays still.",
  }),
  lift({
    id: "lift-tbar",
    title: "T-bar row",
    trainer: "ScottHermanFitness",
    youtubeId: "j3Igk5nyZE4",
    minutes: 4,
    level: "Intermediate",
    kcal: 28,
    equipment: ["Barbell"],
    primary: ["lats", "traps"],
    secondary: ["biceps"],
    pattern: "horizontal-pull",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-row", "lift-cable-row"],
    cue: "Chest proud. Row to the lower ribs. Don't bounce off the stretch.",
  }),
  lift({
    id: "lift-one-arm-row",
    title: "One-arm dumbbell row",
    trainer: "ScottHermanFitness",
    youtubeId: "pYcpY20QaE8",
    minutes: 4,
    level: "Beginner",
    kcal: 22,
    equipment: ["Dumbbells", "Bench"],
    primary: ["lats"],
    secondary: ["biceps", "traps"],
    pattern: "horizontal-pull",
    prescription: "3 × 8–12 / side",
    rest: "90s",
    alternatives: ["lift-cable-row", "lift-inverted"],
    cue: "Row to the hip. Don't rotate the torso into a yoga twist.",
  }),
  lift({
    id: "lift-cable-row",
    title: "Seated cable row",
    trainer: "ScottHermanFitness",
    youtubeId: "GZbfZ033f74",
    minutes: 3,
    level: "Beginner",
    kcal: 22,
    equipment: ["Cable"],
    primary: ["lats"],
    secondary: ["biceps", "traps"],
    pattern: "horizontal-pull",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-one-arm-row", "lift-row"],
    cue: "Row to the hip. Don't rock the torso into a cardio machine.",
  }),
  lift({
    id: "lift-inverted",
    title: "Inverted row",
    trainer: "Calisthenic Movement",
    youtubeId: "hXTc1mDnZCw",
    minutes: 6,
    level: "Beginner",
    kcal: 24,
    equipment: ["Bar"],
    primary: ["lats", "traps"],
    secondary: ["biceps", "abs"],
    pattern: "horizontal-pull",
    prescription: "3 × 6–12",
    rest: "90s",
    alternatives: ["lift-cable-row", "lift-pullup"],
    cue: "Body as a plank. Pull the chest to the bar. Don't pike.",
  }),
  lift({
    id: "lift-pullup",
    title: "The perfect pull-up",
    trainer: "Calisthenic Movement",
    youtubeId: "eGo4IYlbE5g",
    minutes: 8,
    level: "Intermediate",
    kcal: 45,
    equipment: ["Bar"],
    primary: ["lats"],
    secondary: ["biceps", "traps"],
    pattern: "vertical-pull",
    prescription: "4 × 4–10",
    rest: "2 min",
    alternatives: ["lift-chin", "lift-pulldown", "lift-inverted"],
    cue: "Ribs down. Pull elbows to pockets. Chin over, then a full hang.",
  }),
  lift({
    id: "lift-chin",
    title: "Chin-up",
    trainer: "Simonster Strength",
    youtubeId: "e1YSApl-QcM",
    minutes: 7,
    level: "Intermediate",
    kcal: 42,
    equipment: ["Bar"],
    primary: ["lats", "biceps"],
    secondary: ["traps"],
    pattern: "vertical-pull",
    prescription: "4 × 4–10",
    rest: "2 min",
    alternatives: ["lift-pullup", "lift-pulldown"],
    cue: "Supinated grip. Same hollow body as the pull-up. Don't kip.",
  }),
  lift({
    id: "lift-pulldown",
    title: "Lat pulldown",
    trainer: "ScottHermanFitness",
    youtubeId: "CAwf7n6Luuc",
    minutes: 5,
    level: "Beginner",
    kcal: 25,
    equipment: ["Cable"],
    primary: ["lats"],
    secondary: ["biceps", "traps"],
    pattern: "vertical-pull",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-pullup", "lift-straight-arm"],
    cue: "Pull to the upper chest. Don't hide behind the neck.",
  }),
  lift({
    id: "lift-straight-arm",
    title: "Straight-arm pulldown",
    trainer: "ScottHermanFitness",
    youtubeId: "AjCCGN2tU3Q",
    minutes: 3,
    level: "Beginner",
    kcal: 16,
    equipment: ["Cable"],
    primary: ["lats"],
    secondary: ["triceps"],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-pulldown"],
    cue: "Soft elbows. Sweep to the pockets. Don't turn it into a crunch.",
  }),
  lift({
    id: "lift-bb-curl",
    title: "Barbell biceps curl",
    trainer: "ScottHermanFitness",
    youtubeId: "QZEqB6wUPxQ",
    minutes: 5,
    level: "Beginner",
    kcal: 20,
    equipment: ["Barbell"],
    primary: ["biceps"],
    secondary: ["brachialis", "front-delt"],
    pattern: "isolation",
    prescription: "3 × 8–12",
    rest: "60–90s",
    alternatives: ["lift-db-curl", "lift-preacher"],
    cue: "Elbows pinned. No swing. Squeeze at the top, full stretch at the bottom.",
  }),
  lift({
    id: "lift-db-curl",
    title: "Dumbbell biceps curl",
    trainer: "Howcast",
    youtubeId: "ykJmrZ5v0Oo",
    minutes: 3,
    level: "Beginner",
    kcal: 18,
    equipment: ["Dumbbells"],
    primary: ["biceps"],
    secondary: ["brachialis"],
    pattern: "isolation",
    prescription: "3 × 8–12",
    rest: "60s",
    alternatives: ["lift-bb-curl", "lift-hammer"],
    cue: "Supinate as you rise. Elbows stay beside the ribs.",
  }),
  lift({
    id: "lift-hammer",
    title: "Dumbbell hammer curl",
    trainer: "ScottHermanFitness",
    youtubeId: "zC3nLlEvin4",
    minutes: 3,
    level: "Beginner",
    kcal: 18,
    equipment: ["Dumbbells"],
    primary: ["brachialis", "biceps"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "3 × 8–12",
    rest: "60s",
    alternatives: ["lift-db-curl"],
    cue: "Neutral grip. Elbows slightly in front of the hips.",
  }),
  lift({
    id: "lift-preacher",
    title: "Preacher curl",
    trainer: "Jim Stoppani",
    youtubeId: "vngli9UR6Hw",
    minutes: 4,
    level: "Beginner",
    kcal: 18,
    equipment: ["EZ bar"],
    primary: ["biceps"],
    secondary: ["brachialis"],
    pattern: "isolation",
    prescription: "3 × 8–12",
    rest: "60s",
    alternatives: ["lift-bb-curl", "lift-concentration"],
    cue: "Don't hyperextend the elbow at the bottom. Squeeze without the shoulder shrugging.",
  }),
  lift({
    id: "lift-concentration",
    title: "Concentration curl",
    trainer: "ScottHermanFitness",
    youtubeId: "Jvj2wV0vOYU",
    minutes: 3,
    level: "Beginner",
    kcal: 14,
    equipment: ["Dumbbells"],
    primary: ["biceps"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 10–15 / arm",
    rest: "45s",
    alternatives: ["lift-preacher"],
    cue: "Elbow parked on the inner thigh. No torso English.",
  }),
  lift({
    id: "lift-skull",
    title: "Skull crushers",
    trainer: "ScottHermanFitness",
    youtubeId: "RavQHfFxbdA",
    minutes: 5,
    level: "Beginner",
    kcal: 22,
    equipment: ["EZ bar", "Bench"],
    primary: ["triceps"],
    secondary: ["chest"],
    pattern: "isolation",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-overhead-tri", "lift-pushdown"],
    cue: "Elbows in. Lower behind the head slightly — it's an extension, not a pullover.",
  }),
  lift({
    id: "lift-overhead-tri",
    title: "Overhead tricep extension",
    trainer: "ScottHermanFitness",
    youtubeId: "-Vyt2QdsR7E",
    minutes: 4,
    level: "Beginner",
    kcal: 18,
    equipment: ["Dumbbells"],
    primary: ["triceps"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-skull", "lift-pushdown"],
    cue: "Elbows by the ears. Stretch the long head. Don't flare into a press.",
  }),
  lift({
    id: "lift-pushdown",
    title: "Tricep pushdown",
    trainer: "ScottHermanFitness",
    youtubeId: "2-LAMcpzODU",
    minutes: 3,
    level: "Beginner",
    kcal: 18,
    equipment: ["Cable"],
    primary: ["triceps"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-kickback", "lift-overhead-tri"],
    cue: "Elbows in front of the hips. Full lockout, then just past 90 on the way up.",
  }),
  lift({
    id: "lift-kickback",
    title: "Tricep kickback",
    trainer: "ScottHermanFitness",
    youtubeId: "6SS6K3lAwZ8",
    minutes: 3,
    level: "Beginner",
    kcal: 14,
    equipment: ["Dumbbells"],
    primary: ["triceps"],
    secondary: [],
    pattern: "isolation",
    prescription: "3 × 12–15 / arm",
    rest: "45s",
    alternatives: ["lift-pushdown"],
    cue: "Upper arm glued to the torso. Only the forearm moves.",
  }),
  lift({
    id: "lift-plank",
    title: "Front plank",
    trainer: "ATHLEAN-X",
    youtubeId: "xVrALzPc7dM",
    minutes: 5,
    level: "Beginner",
    kcal: 16,
    equipment: ["None"],
    primary: ["abs"],
    secondary: ["obliques", "front-delt"],
    pattern: "core",
    prescription: "3 × 30–60s",
    rest: "45s",
    alternatives: ["lift-hollow", "lift-dead-bug"],
    cue: "Ribs down, glutes on. Don't hang in the low back.",
  }),
  lift({
    id: "lift-side-plank",
    title: "Side plank",
    trainer: "Howcast",
    youtubeId: "NXr4Fw8q60o",
    minutes: 4,
    level: "Beginner",
    kcal: 14,
    equipment: ["None"],
    primary: ["obliques"],
    secondary: ["abs", "glutes"],
    pattern: "core",
    prescription: "3 × 20–45s / side",
    rest: "45s",
    alternatives: ["lift-pallof"],
    cue: "Hips stacked. Don't rotate the chest to the floor.",
  }),
  lift({
    id: "lift-hollow",
    title: "Hollow body hold",
    trainer: "FitnessFAQs",
    youtubeId: "uZqTUwq96iU",
    minutes: 5,
    level: "Intermediate",
    kcal: 16,
    equipment: ["None"],
    primary: ["abs"],
    secondary: ["quads"],
    pattern: "core",
    prescription: "3 × 20–40s",
    rest: "45s",
    alternatives: ["lift-plank", "lift-dead-bug"],
    cue: "Low back glued. Arms and legs long. Shorten the levers if you peel up.",
  }),
  lift({
    id: "lift-dead-bug",
    title: "Dead bug",
    trainer: "ATHLEAN-X",
    youtubeId: "4XLEnwUr1d8",
    minutes: 5,
    level: "Beginner",
    kcal: 14,
    equipment: ["None"],
    primary: ["abs"],
    secondary: ["obliques"],
    pattern: "core",
    prescription: "3 × 8–12 / side",
    rest: "45s",
    alternatives: ["lift-bird-dog", "lift-hollow"],
    cue: "Exhale as the limbs travel. If the ribs flare, you've gone too far.",
  }),
  lift({
    id: "lift-bird-dog",
    title: "Bird dog",
    trainer: "ATHLEAN-X",
    youtubeId: "wiFNA3sqjCA",
    minutes: 4,
    level: "Beginner",
    kcal: 12,
    equipment: ["None"],
    primary: ["abs", "glutes"],
    secondary: ["obliques"],
    pattern: "core",
    prescription: "3 × 8 / side",
    rest: "45s",
    alternatives: ["lift-dead-bug"],
    cue: "Reach long, don't lift high. Square hips. Pause.",
  }),
  lift({
    id: "lift-hanging-raise",
    title: "Hanging leg raise",
    trainer: "Calisthenic Movement",
    youtubeId: "Pr1ieGZ5atk",
    minutes: 6,
    level: "Intermediate",
    kcal: 22,
    equipment: ["Bar"],
    primary: ["abs"],
    secondary: ["obliques", "lats"],
    pattern: "core",
    prescription: "3 × 6–12",
    rest: "90s",
    alternatives: ["lift-ab-wheel", "lift-cable-crunch"],
    cue: "Posterior tilt first. Legs follow. Don't swing into a kip.",
  }),
  lift({
    id: "lift-ab-wheel",
    title: "Ab wheel rollout",
    trainer: "ATHLEAN-X",
    youtubeId: "5I3LgiumTJM",
    minutes: 6,
    level: "Advanced",
    kcal: 24,
    equipment: ["Ab wheel"],
    primary: ["abs"],
    secondary: ["lats", "front-delt"],
    pattern: "core",
    prescription: "3 × 6–12",
    rest: "90s",
    alternatives: ["lift-plank", "lift-hanging-raise"],
    cue: "Hips and shoulders travel together. Stop before the low back sags.",
  }),
  lift({
    id: "lift-pallof",
    title: "Pallof press",
    trainer: "ATHLEAN-X",
    youtubeId: "AH_QZLm_0-s",
    minutes: 5,
    level: "Beginner",
    kcal: 14,
    equipment: ["Cable"],
    primary: ["obliques", "abs"],
    secondary: ["glutes"],
    pattern: "core",
    prescription: "3 × 8–12 / side",
    rest: "45s",
    alternatives: ["lift-woodchop", "lift-side-plank"],
    cue: "Press out, don't rotate. Glutes on. The cable wants to spin you — you don't let it.",
  }),
  lift({
    id: "lift-woodchop",
    title: "Cable woodchop",
    trainer: "ScottHermanFitness",
    youtubeId: "pAplQXk3dkU",
    minutes: 4,
    level: "Beginner",
    kcal: 18,
    equipment: ["Cable"],
    primary: ["obliques"],
    secondary: ["abs", "front-delt"],
    pattern: "core",
    prescription: "3 × 8–12 / side",
    rest: "60s",
    alternatives: ["lift-pallof", "lift-russian"],
    cue: "Rotate through the ribcage, not the lumbar. Arms are the rope, core is the motor.",
  }),
  lift({
    id: "lift-russian",
    title: "Russian twist",
    trainer: "Howcast",
    youtubeId: "wkD8rjkodUI",
    minutes: 3,
    level: "Beginner",
    kcal: 16,
    equipment: ["None"],
    primary: ["obliques", "abs"],
    secondary: [],
    pattern: "core",
    prescription: "3 × 16–24",
    rest: "45s",
    alternatives: ["lift-woodchop"],
    cue: "Lean with a long spine. Rotate, don't flop the shoulders.",
  }),
  lift({
    id: "lift-cable-crunch",
    title: "Cable crunch",
    trainer: "ScottHermanFitness",
    youtubeId: "2fbujeH3F0E",
    minutes: 3,
    level: "Beginner",
    kcal: 16,
    equipment: ["Cable"],
    primary: ["abs"],
    secondary: [],
    pattern: "core",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-hanging-raise"],
    cue: "Crunch the ribs to the pelvis. Hips stay put. This is not a hip hinge.",
  }),
  lift({
    id: "lift-farmer",
    title: "Farmer carry",
    trainer: "ATHLEAN-X",
    youtubeId: "rt17lmnaLSM",
    minutes: 5,
    level: "Beginner",
    kcal: 30,
    equipment: ["Dumbbells"],
    primary: ["traps", "abs"],
    secondary: ["glutes", "calves"],
    pattern: "carry",
    prescription: "4 × 30–40 m",
    rest: "90s",
    alternatives: ["lift-shrug"],
    cue: "Pack the shoulders. Ribs down. Walk like you own the hallway.",
  }),
  lift({
    id: "lift-kb-swing",
    title: "Kettlebell swing",
    trainer: "Mark Wildman",
    youtubeId: "YSxHifyI6s8",
    minutes: 8,
    level: "Intermediate",
    kcal: 40,
    equipment: ["Kettlebell"],
    primary: ["glutes", "hamstrings"],
    secondary: ["abs", "lats"],
    pattern: "hinge",
    prescription: "5 × 10–15",
    rest: "60s",
    alternatives: ["lift-rdl", "lift-deadlift"],
    cue: "Hinge, snap, float. Arms are ropes. Don't squat the bell up.",
  }),
  lift({
    id: "lift-clean",
    title: "Power clean",
    trainer: "Catalyst Athletics",
    youtubeId: "YG8M_-11C2A",
    minutes: 10,
    level: "Advanced",
    kcal: 45,
    equipment: ["Barbell"],
    primary: ["quads", "glutes", "traps"],
    secondary: ["hamstrings", "front-delt"],
    pattern: "olympic",
    prescription: "5 × 2–3",
    rest: "2–3 min",
    alternatives: ["lift-kb-swing", "lift-deadlift"],
    cue: "Jump the bar up, don't row it. Catch quiet. This is timing, not a max pull.",
  }),
  lift({
    id: "lift-thruster",
    title: "Barbell thruster",
    trainer: "CrossFit",
    youtubeId: "aea5BGj9a8Y",
    minutes: 5,
    level: "Intermediate",
    kcal: 40,
    equipment: ["Barbell"],
    primary: ["quads", "front-delt"],
    secondary: ["glutes", "triceps"],
    pattern: "squat",
    prescription: "4 × 6–10",
    rest: "2 min",
    alternatives: ["lift-goblet", "lift-ohp"],
    cue: "Squat, then drive. The press starts from the legs, not the low back.",
  }),
  lift({
    id: "lift-tgu",
    title: "Turkish get-up",
    trainer: "Onnit",
    youtubeId: "0bWRPC49-KI",
    minutes: 9,
    level: "Intermediate",
    kcal: 35,
    equipment: ["Kettlebell"],
    primary: ["abs", "front-delt", "glutes"],
    secondary: ["obliques", "triceps"],
    pattern: "core",
    prescription: "3 × 3 / side",
    rest: "90s",
    alternatives: ["lift-ohp", "lift-pallof"],
    cue: "Eyes on the bell. Slow is skilled. Each position is a pause, not a scramble.",
  }),
  lift({
    id: "lift-box-jump",
    title: "Box jump",
    trainer: "CrossFit",
    youtubeId: "NBY9-kTuHEk",
    minutes: 4,
    level: "Intermediate",
    kcal: 28,
    equipment: ["Box"],
    primary: ["quads", "glutes"],
    secondary: ["calves"],
    pattern: "plyo",
    prescription: "4 × 5",
    rest: "90s",
    alternatives: ["lift-squat"],
    cue: "Soft landing. Step down. Height is ego; quiet feet are the skill.",
  }),
  lift({
    id: "lift-burpee",
    title: "Burpee",
    trainer: "Well+Good",
    youtubeId: "qLBImHhCXSw",
    minutes: 3,
    level: "Intermediate",
    kcal: 35,
    equipment: ["None"],
    primary: ["chest", "quads", "abs"],
    secondary: ["triceps", "glutes"],
    pattern: "condition",
    prescription: "EMOM 8–10 × 5–8",
    rest: "the leftover minute",
    alternatives: ["lift-pushup", "lift-thruster"],
    cue: "Chest to deck, jump if you can. Don't worm the push-up.",
  }),
  lift({
    id: "lift-machine-press",
    title: "Machine chest press",
    trainer: "ScottHermanFitness",
    youtubeId: "xUm0BiZCWlQ",
    minutes: 4,
    level: "Beginner",
    kcal: 28,
    equipment: ["Machine"],
    primary: ["chest"],
    secondary: ["triceps", "front-delt"],
    pattern: "horizontal-push",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-bench", "lift-db-press", "lift-pushup"],
    cue: "Scapulae set. Don't bounce the stack. Pause a finger off the chest.",
  }),
  lift({
    id: "lift-pec-deck",
    title: "Pec deck fly",
    trainer: "Max Euceda",
    youtubeId: "3jYo5cMU3d4",
    minutes: 3,
    level: "Beginner",
    kcal: 18,
    equipment: ["Machine"],
    primary: ["chest"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-fly", "lift-crossover"],
    cue: "Soft elbows. Sweep, don't punch. Stop before the shoulders dump forward.",
  }),
  lift({
    id: "lift-chest-row",
    title: "Chest-supported row",
    trainer: "Seriously Strong Training",
    youtubeId: "vmX58YYK3-8",
    minutes: 5,
    level: "Beginner",
    kcal: 28,
    equipment: ["Dumbbells", "Bench"],
    primary: ["lats", "traps"],
    secondary: ["biceps"],
    pattern: "horizontal-pull",
    prescription: "4 × 8–12",
    rest: "90s",
    alternatives: ["lift-row", "lift-one-arm-row", "lift-cable-row"],
    cue: "Chest glued to the pad. Pull to the hip. No torso heave.",
  }),
  lift({
    id: "lift-push-press",
    title: "Push press",
    trainer: "Catalyst Athletics",
    youtubeId: "yklSQG1_Ovc",
    minutes: 6,
    level: "Intermediate",
    kcal: 32,
    equipment: ["Barbell"],
    primary: ["front-delt", "triceps"],
    secondary: ["quads", "abs"],
    pattern: "vertical-push",
    prescription: "5 × 3",
    rest: "2 min",
    alternatives: ["lift-ohp", "lift-thruster", "lift-landmine"],
    cue: "Dip-drive, then press. Legs start it; arms finish it. Don't press-press-press from a soft lockout.",
  }),
  lift({
    id: "lift-sl-rdl",
    title: "Single-leg RDL",
    trainer: "ScottHermanFitness",
    youtubeId: "DGavj41F_Cs",
    minutes: 5,
    level: "Intermediate",
    kcal: 24,
    equipment: ["Dumbbells"],
    primary: ["hamstrings", "glutes"],
    secondary: ["abs"],
    pattern: "hinge",
    prescription: "3 × 8 / side",
    rest: "90s",
    alternatives: ["lift-rdl", "lift-bss"],
    cue: "Square hips. Reach the back heel to the wall. Soft knee, long spine.",
  }),
  lift({
    id: "lift-hyper",
    title: "45° back extension",
    trainer: "Precision Wellbeing",
    youtubeId: "-MTjHC3NC2s",
    minutes: 4,
    level: "Beginner",
    kcal: 22,
    equipment: ["Machine"],
    primary: ["glutes", "hamstrings"],
    secondary: ["lats"],
    pattern: "hinge",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-rdl", "lift-good-morning", "lift-hip-thrust"],
    cue: "Hinge at the hips, not a sit-up. Squeeze glutes to stand, don't yank lumbar.",
  }),
  lift({
    id: "lift-adductor",
    title: "Hip adduction machine",
    trainer: "Colossus Fitness",
    youtubeId: "MLBm7i341Rw",
    minutes: 3,
    level: "Beginner",
    kcal: 16,
    equipment: ["Machine"],
    primary: ["quads"],
    secondary: ["glutes"],
    pattern: "isolation",
    prescription: "3 × 12–20",
    rest: "60s",
    alternatives: ["lift-hip-abductor", "lift-lunge"],
    cue: "Squeeze in, don't slam. Inner thigh is the mover — the stack is not a toy.",
  }),
  lift({
    id: "lift-wall-sit",
    title: "Wall sit",
    trainer: "Well+Good",
    youtubeId: "JaZNYM3zAP0",
    minutes: 3,
    level: "Beginner",
    kcal: 18,
    equipment: ["None"],
    primary: ["quads"],
    secondary: ["glutes", "abs"],
    pattern: "squat",
    prescription: "4 × 30–60s",
    rest: "60s",
    alternatives: ["lift-squat", "lift-goblet"],
    cue: "Knees over ankles, back flat to the wall. Quads should complain before the low back does.",
  }),
  lift({
    id: "lift-toes-bar",
    title: "Toes-to-bar",
    trainer: "WODprep",
    youtubeId: "kjYuPnmMjfo",
    minutes: 6,
    level: "Advanced",
    kcal: 30,
    equipment: ["Bar"],
    primary: ["abs"],
    secondary: ["lats", "obliques"],
    pattern: "core",
    prescription: "4 × 6–10",
    rest: "90s",
    alternatives: ["lift-hanging-raise", "lift-hollow"],
    cue: "Hollow first. Toes to the bar, not a wild kip. Compress, then reach.",
  }),
  lift({
    id: "lift-bicycle",
    title: "Bicycle crunch",
    trainer: "UCLA Health",
    youtubeId: "eqg47ZuGZXQ",
    minutes: 3,
    level: "Beginner",
    kcal: 16,
    equipment: ["None"],
    primary: ["abs", "obliques"],
    pattern: "core",
    prescription: "3 × 16–24",
    rest: "45s",
    alternatives: ["lift-dead-bug", "lift-russian"],
    cue: "Slow. Shoulder toward opposite knee, not elbow to nowhere. Low back stays heavy.",
  }),
  lift({
    id: "lift-lsit",
    title: "L-sit progression",
    trainer: "Vitality",
    youtubeId: "HxDP7SqggpI",
    minutes: 6,
    level: "Intermediate",
    kcal: 20,
    equipment: ["None"],
    primary: ["abs", "quads"],
    secondary: ["triceps"],
    pattern: "core",
    prescription: "5 × 10–20s",
    rest: "60s",
    alternatives: ["lift-hollow", "lift-hanging-raise"],
    cue: "Lock the elbows. Depress the scapulae. Legs as long as you can keep from collapsing.",
  }),
  lift({
    id: "lift-deadhang",
    title: "Dead hang",
    trainer: "Dr. Jon Saunders",
    youtubeId: "NUv1WpYA_x8",
    minutes: 4,
    level: "Beginner",
    kcal: 10,
    equipment: ["Bar"],
    primary: ["lats"],
    secondary: ["biceps"],
    pattern: "vertical-pull",
    prescription: "4 × 20–45s",
    rest: "60s",
    alternatives: ["lift-pullup", "lift-inverted"],
    cue: "Ribs down. Shoulders in their sockets, not shrugged into the ears. Breathe.",
  }),
  lift({
    id: "lift-cable-curl",
    title: "Cable biceps curl",
    trainer: "ScottHermanFitness",
    youtubeId: "AsAVbj7puKo",
    minutes: 4,
    level: "Beginner",
    kcal: 16,
    equipment: ["Cable"],
    primary: ["biceps"],
    secondary: ["brachialis"],
    pattern: "isolation",
    prescription: "3 × 10–15",
    rest: "60s",
    alternatives: ["lift-bb-curl", "lift-db-curl"],
    cue: "Elbows pinned. Squeeze at the top. Don't let the stack yank you into a lean.",
  }),
  lift({
    id: "lift-machine-ohp",
    title: "Machine shoulder press",
    trainer: "ScottHermanFitness",
    youtubeId: "Wqq43dKW1TU",
    minutes: 4,
    level: "Beginner",
    kcal: 24,
    equipment: ["Machine"],
    primary: ["front-delt"],
    secondary: ["triceps"],
    pattern: "vertical-push",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-ohp", "lift-db-press", "lift-arnold"],
    cue: "Don't shrug the last inch. Head through at the top. Ribs stacked.",
  }),
  lift({
    id: "lift-upright",
    title: "Barbell upright row",
    trainer: "ScottHermanFitness",
    youtubeId: "amCU-ziHITM",
    minutes: 4,
    level: "Intermediate",
    kcal: 20,
    equipment: ["Barbell"],
    primary: ["front-delt", "traps"],
    secondary: ["biceps"],
    pattern: "vertical-pull",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-lateral", "lift-facepull"],
    cue: "Wide-ish grip. Elbows lead. Stop at the chest — don't crank into a shrug behind the neck.",
  }),
  lift({
    id: "lift-hspu",
    title: "Handstand push-up",
    trainer: "Calisthenic Movement",
    youtubeId: "h0HjqYRlXYg",
    minutes: 8,
    level: "Advanced",
    kcal: 30,
    equipment: ["None"],
    primary: ["front-delt", "triceps"],
    secondary: ["abs", "traps"],
    pattern: "vertical-push",
    prescription: "5 × 3–6",
    rest: "2 min",
    alternatives: ["lift-pike-push", "lift-ohp"],
    cue: "Hollow body against the wall. Head to a mat, not a broken neck. Pike first if this isn't honest.",
  }),
  lift({
    id: "lift-muscleup",
    title: "Muscle-up",
    trainer: "Calisthenic Movement",
    youtubeId: "89v8LYbgg5M",
    minutes: 8,
    level: "Advanced",
    kcal: 32,
    equipment: ["Bar"],
    primary: ["lats", "triceps", "chest"],
    secondary: ["abs", "biceps"],
    pattern: "vertical-pull",
    prescription: "5 × 1–3",
    rest: "2–3 min",
    alternatives: ["lift-pullup", "lift-dip", "lift-chin"],
    cue: "False grip or a clean transition. Pull high before you try to turn over. No ugly kip as a habit.",
  }),
  lift({
    id: "lift-kb-snatch",
    title: "Kettlebell snatch",
    trainer: "StrongFirst",
    youtubeId: "AR6E01ABoHk",
    minutes: 6,
    level: "Advanced",
    kcal: 35,
    equipment: ["Kettlebell"],
    primary: ["glutes", "hamstrings", "front-delt"],
    secondary: ["lats", "abs"],
    pattern: "olympic",
    prescription: "5 × 5 / side",
    rest: "90s",
    alternatives: ["lift-kb-swing", "lift-clean", "lift-tgu"],
    cue: "Hike, hip pop, punch through. The bell floats; you don't muscle it around the wrist.",
  }),
  lift({
    id: "lift-suitcase",
    title: "Suitcase carry",
    trainer: "Squat University",
    youtubeId: "LJaq4BS7KpE",
    minutes: 5,
    level: "Beginner",
    kcal: 28,
    equipment: ["Dumbbells"],
    primary: ["obliques", "abs"],
    secondary: ["glutes", "quads"],
    pattern: "carry",
    prescription: "4 × 20–40 m / side",
    rest: "60s",
    alternatives: ["lift-farmer", "lift-pallof"],
    cue: "Ribs stacked. Don't lean away from the load. Walk like you're unpaid to look dramatic.",
  }),
  lift({
    id: "lift-battle",
    title: "Battle ropes",
    trainer: "Criticalbench",
    youtubeId: "pQb2xIGioyQ",
    minutes: 6,
    level: "Beginner",
    kcal: 50,
    equipment: ["Ropes"],
    primary: ["front-delt", "abs"],
    secondary: ["quads", "lats"],
    pattern: "condition",
    prescription: "8–10 × 20s on / 40s off",
    rest: "the rest interval",
    alternatives: ["lift-burpee", "lift-kb-swing"],
    cue: "Soft knees. Waves from the shoulders, not a panicked shrug. Keep the slack out.",
  }),
  lift({
    id: "lift-mountain",
    title: "Mountain climber",
    trainer: "Hinge Health",
    youtubeId: "4edD9cyQF6I",
    minutes: 3,
    level: "Beginner",
    kcal: 22,
    equipment: ["None"],
    primary: ["abs", "quads"],
    secondary: ["front-delt"],
    pattern: "condition",
    prescription: "4 × 20–40s",
    rest: "45s",
    alternatives: ["lift-plank", "lift-burpee"],
    cue: "Plank first. Drive the knee, don't bounce the hips. Quiet shoulders.",
  }),
  lift({
    id: "lift-incline-curl",
    title: "Incline dumbbell curl",
    trainer: "ScottHermanFitness",
    youtubeId: "soxrZlIl35U",
    minutes: 4,
    level: "Intermediate",
    kcal: 16,
    equipment: ["Dumbbells", "Bench"],
    primary: ["biceps"],
    secondary: ["brachialis"],
    pattern: "isolation",
    prescription: "3 × 8–12",
    rest: "60s",
    alternatives: ["lift-db-curl", "lift-cable-curl"],
    cue: "Arms hang. Stretch at the bottom, don't swing. Elbows stay behind the torso.",
  }),
  lift({
    id: "lift-close-pulldown",
    title: "Reverse-grip pulldown",
    trainer: "ScottHermanFitness",
    youtubeId: "apzFTbsm7HU",
    minutes: 4,
    level: "Beginner",
    kcal: 24,
    equipment: ["Cable"],
    primary: ["lats", "biceps"],
    secondary: ["traps"],
    pattern: "vertical-pull",
    prescription: "3 × 8–12",
    rest: "90s",
    alternatives: ["lift-pulldown", "lift-chin"],
    cue: "Chest up. Pull to the collarbone. Don't turn it into a behind-the-neck circus.",
  }),
  lift({
    id: "lift-external",
    title: "Shoulder external rotation",
    trainer: "Scott Neubauer",
    youtubeId: "vsF3VgMTCEU",
    minutes: 4,
    level: "Beginner",
    kcal: 10,
    equipment: ["Cable"],
    primary: ["traps"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "3 × 12–20 / side",
    rest: "45s",
    alternatives: ["lift-facepull", "lift-rear-fly"],
    cue: "Elbow glued to the rib. Rotate the forearm, don't row. Light load, honest range.",
  }),
  lift({
    id: "lift-pull-apart",
    title: "Band face pull / pull-apart",
    trainer: "Men's Health",
    youtubeId: "CSP7YpPv3ds",
    minutes: 3,
    level: "Beginner",
    kcal: 12,
    equipment: ["Band"],
    primary: ["traps"],
    secondary: ["front-delt"],
    pattern: "horizontal-pull",
    prescription: "3 × 15–25",
    rest: "45s",
    alternatives: ["lift-facepull", "lift-rear-fly"],
    cue: "Thumbs back. Pull to the face, not the throat. Own the squeeze for a count.",
  }),
];
