import { labelsFor } from "./muscles";
import type { Workout } from "./types";

function session(
  row: Omit<Workout, "kind" | "muscles"> & {
    primary?: Workout["primary"];
    secondary?: Workout["secondary"];
  },
): Workout {
  return {
    ...row,
    kind: "session",
    muscles: labelsFor(row.primary, row.secondary).length
      ? labelsFor(row.primary, row.secondary)
      : row.category
        ? [row.category]
        : ["Session"],
  };
}

/** Follow-along films — press play and move. */
export const SESSION_VIDEOS: Workout[] = [
  session({
    id: "full-body",
    title: "20 min full-body strength",
    trainer: "Pamela Reif",
    youtubeId: "UBMk30rjy0o",
    minutes: 20,
    level: "Intermediate",
    kcal: 240,
    category: "Strength",
    equipment: ["Mat"],
    primary: ["quads", "glutes", "chest", "abs"],
    secondary: ["lats", "front-delt"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Keep ribs stacked. Last 4 reps should feel honest.",
  }),
  session({
    id: "beginner-strength",
    title: "Beginner strength — dumbbells",
    trainer: "HASfit",
    youtubeId: "RPi9aJGuRDM",
    minutes: 32,
    level: "Beginner",
    kcal: 180,
    category: "Strength",
    equipment: ["Dumbbells", "Mat"],
    primary: ["quads", "chest", "lats", "glutes"],
    secondary: ["abs"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Learn the patterns slow. The load can wait a month.",
  }),
  session({
    id: "yoga-beginner",
    title: "Yoga for complete beginners",
    trainer: "Yoga with Adriene",
    youtubeId: "v7AYKMP6rOE",
    minutes: 20,
    level: "Beginner",
    kcal: 80,
    category: "Yoga",
    equipment: ["Mat"],
    primary: ["hamstrings", "glutes", "abs"],
    secondary: ["lats"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "If the neck gripes, look slightly down.",
  }),
  session({
    id: "session-yoga-30",
    title: "30 min yoga flow",
    trainer: "Yoga with Adriene",
    youtubeId: "PeWuJY7J2Gs",
    minutes: 30,
    level: "Beginner",
    kcal: 110,
    category: "Yoga",
    equipment: ["Mat"],
    primary: ["hamstrings", "glutes", "abs"],
    secondary: ["lats", "calves"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Breathe louder than you move. Skip anything that pinches.",
  }),
  session({
    id: "session-yoga-morning",
    title: "Morning yoga wake-up",
    trainer: "Yoga with Adriene",
    youtubeId: "UEEsdXn8oG8",
    minutes: 16,
    level: "Beginner",
    kcal: 60,
    category: "Yoga",
    equipment: ["Mat"],
    primary: ["abs", "hamstrings"],
    secondary: ["glutes"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Soft knees. This is a start, not a max-effort class.",
  }),
  session({
    id: "session-yin",
    title: "Yin yoga — hips and hamstrings",
    trainer: "Yoga with Kassandra",
    youtubeId: "KyHnpaQkFCI",
    minutes: 40,
    level: "Beginner",
    kcal: 90,
    category: "Yoga",
    equipment: ["Mat"],
    primary: ["hamstrings", "glutes"],
    secondary: ["abs"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Hold, don't stretch-fight. Back out of anything sharp.",
  }),
  session({
    id: "session-pilates",
    title: "Pilates — 20 min core",
    trainer: "Move with Nicole",
    youtubeId: "y2RcYo36boM",
    minutes: 20,
    level: "Intermediate",
    kcal: 140,
    category: "Pilates",
    equipment: ["Mat"],
    primary: ["abs", "obliques", "glutes"],
    secondary: ["quads"],
    pattern: "core",
    prescription: "Follow the film",
    cue: "Exhale on the effort. Neck long. Small range beats sloppy range.",
  }),
  session({
    id: "hiit-cardio",
    title: "HIIT cardio — no equipment",
    trainer: "SELF",
    youtubeId: "ml6cT4AZdqI",
    minutes: 25,
    level: "Advanced",
    kcal: 330,
    category: "HIIT",
    equipment: ["None"],
    primary: ["quads", "glutes"],
    secondary: ["abs", "calves"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Sprint the work, own the rest. Do not race the demo.",
  }),
  session({
    id: "core",
    title: "10 min ab workout",
    trainer: "Pamela Reif",
    youtubeId: "AnYl6Nk9GOA",
    minutes: 12,
    level: "Intermediate",
    kcal: 110,
    category: "Core",
    equipment: ["None"],
    primary: ["abs", "obliques"],
    pattern: "core",
    prescription: "Follow the film",
    cue: "Exhale on the crunch. Quiet the hip flexors.",
  }),
  session({
    id: "session-chloe-core",
    title: "Core circuit — Chloe Ting",
    trainer: "Chloe Ting",
    youtubeId: "2pLT-olgUJs",
    minutes: 15,
    level: "Beginner",
    kcal: 90,
    category: "Core",
    equipment: ["None"],
    primary: ["abs", "obliques"],
    pattern: "core",
    prescription: "Follow the film",
    cue: "Slow the sit-up. If the hip flexors take over, shorten the lever.",
  }),
  session({
    id: "session-mobility",
    title: "Full-body stretch + mobility",
    trainer: "Boho Beautiful",
    youtubeId: "g_tea8ZNk5A",
    minutes: 20,
    level: "Beginner",
    kcal: 70,
    category: "Mobility",
    equipment: ["Mat"],
    primary: ["hamstrings", "glutes", "lats"],
    secondary: ["calves", "abs"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "End-range is a conversation, not a fight.",
  }),
  session({
    id: "session-hips",
    title: "Hip mobility flow",
    trainer: "Yoga with Adriene",
    youtubeId: "Ho9em79_0qg",
    minutes: 18,
    level: "Beginner",
    kcal: 60,
    category: "Mobility",
    equipment: ["Mat"],
    primary: ["glutes", "hamstrings"],
    secondary: ["quads"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Breathe into the pinch. Don't force frog pose.",
  }),
  session({
    id: "run-form",
    title: "How to run properly",
    trainer: "Global Triathlon Network",
    youtubeId: "brFHyOtTwH4",
    minutes: 12,
    level: "Beginner",
    kcal: 50,
    category: "Running",
    equipment: ["Shoes"],
    primary: ["quads", "calves"],
    secondary: ["glutes", "abs"],
    pattern: "condition",
    prescription: "Watch, then 20 min easy",
    cue: "Cadence first, stride second. Land under you.",
  }),
  session({
    id: "session-zone2",
    title: "Zone-2 cardio — why it works",
    trainer: "Huberman Lab",
    youtubeId: "L5J6sgQLvuE",
    minutes: 12,
    level: "Beginner",
    kcal: 80,
    category: "Cardio",
    equipment: ["Shoes"],
    primary: ["glutes", "calves"],
    secondary: ["abs"],
    pattern: "condition",
    prescription: "Watch, then 30–45 min easy",
    cue: "Nose breathing. You can talk, you cannot sing. This is the boring engine work that works.",
  }),
  session({
    id: "session-jump-rope",
    title: "10 min jump rope",
    trainer: "Jump Rope Dudes",
    youtubeId: "FJmRQ5iTXKE",
    minutes: 10,
    level: "Beginner",
    kcal: 120,
    category: "Cardio",
    equipment: ["Jump rope"],
    primary: ["calves", "quads"],
    secondary: ["abs", "front-delt"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Quiet feet. Wrists turn the rope, not the shoulders.",
  }),
  session({
    id: "session-boxing",
    title: "Boxing cardio — no bag needed",
    trainer: "FightCamp",
    youtubeId: "7CZ5I-PZjEg",
    minutes: 20,
    level: "Intermediate",
    kcal: 240,
    category: "Boxing",
    equipment: ["None"],
    primary: ["front-delt", "abs", "quads"],
    secondary: ["calves", "obliques"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Hands up on the rest. Snap the punch, don't shove it.",
  }),
  session({
    id: "session-dance",
    title: "Dance cardio",
    trainer: "Body Project",
    youtubeId: "gC_L9qAHVJ8",
    minutes: 15,
    level: "Beginner",
    kcal: 160,
    category: "Cardio",
    equipment: ["None"],
    primary: ["quads", "glutes"],
    secondary: ["calves", "abs"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Smile through the messy reps. Range over looking cool.",
  }),
  session({
    id: "session-kb",
    title: "Kettlebell — 20 min",
    trainer: "Caroline Girvan",
    youtubeId: "VCcar3MA07w",
    minutes: 20,
    level: "Intermediate",
    kcal: 220,
    category: "Strength",
    equipment: ["Kettlebell", "Mat"],
    primary: ["glutes", "hamstrings", "abs"],
    secondary: ["lats", "front-delt"],
    pattern: "hinge",
    prescription: "Follow the film",
    cue: "Hinge the swings. Pack the shoulder on the get-ups.",
  }),
  session({
    id: "session-cycle",
    title: "Indoor cycling intervals",
    trainer: "GCN Training",
    youtubeId: "wjAYieMdQbQ",
    minutes: 30,
    level: "Intermediate",
    kcal: 280,
    category: "Cycling",
    equipment: ["Bike"],
    primary: ["quads", "glutes"],
    secondary: ["calves", "abs"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Cadence on the recoveries. Don't mash a gear you can't spin.",
  }),
  session({
    id: "session-row",
    title: "Rowing form + 20 min",
    trainer: "Concept2",
    youtubeId: "4zWu1yuJ0_g",
    minutes: 12,
    level: "Beginner",
    kcal: 90,
    category: "Cardio",
    equipment: ["Rower"],
    primary: ["lats", "quads", "hamstrings"],
    secondary: ["abs", "calves"],
    pattern: "condition",
    prescription: "Watch, then 20 min at 18–22 spm",
    cue: "Legs, then body, then arms. Reverse to come forward. Don't yank with the low back.",
  }),
  session({
    id: "session-foam",
    title: "Foam roll recovery",
    trainer: "ATHLEAN-X",
    youtubeId: "Bq6NcAoQDSk",
    minutes: 10,
    level: "Beginner",
    kcal: 40,
    category: "Mobility",
    equipment: ["Foam roller"],
    primary: ["quads", "glutes", "lats"],
    secondary: ["calves"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Slow passes. Skip the lumbar spine. Breathe on the tender spots.",
  }),
  session({
    id: "session-walk",
    title: "30 min indoor walk",
    trainer: "Walk at Home",
    youtubeId: "AEREJOT_Mpc",
    minutes: 30,
    level: "Beginner",
    kcal: 140,
    category: "Cardio",
    equipment: ["Shoes"],
    primary: ["quads", "glutes", "calves"],
    secondary: ["abs"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Talk test. Arms swing. This is the session people actually stick to.",
  }),
  session({
    id: "session-swim",
    title: "Beginner swim sessions",
    trainer: "Global Triathlon Network",
    youtubeId: "AhvXzPbz1QA",
    minutes: 14,
    level: "Beginner",
    kcal: 80,
    category: "Swim",
    equipment: ["Pool"],
    primary: ["lats", "front-delt"],
    secondary: ["quads", "abs"],
    pattern: "condition",
    prescription: "Watch, then 20–30 min easy",
    cue: "Tall body, quiet kick. Bilateral breathing when it doesn't steal the stroke.",
  }),
  session({
    id: "session-barre",
    title: "20 min barre — full body",
    trainer: "Action Jacquelyn",
    youtubeId: "IaUJFHbH-dQ",
    minutes: 20,
    level: "Beginner",
    kcal: 160,
    category: "Barre",
    equipment: ["None"],
    primary: ["glutes", "quads", "abs"],
    secondary: ["calves"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Tiny range, honest tension. Don't bounce the knee past the toe.",
  }),
  session({
    id: "session-airbike",
    title: "15 min fan-bike HIIT",
    trainer: "Sunny Health & Fitness",
    youtubeId: "rbmIkBB-dJY",
    minutes: 15,
    level: "Intermediate",
    kcal: 200,
    category: "HIIT",
    equipment: ["Bike"],
    primary: ["quads", "glutes"],
    secondary: ["lats", "abs"],
    pattern: "condition",
    prescription: "Follow the film",
    cue: "Push and pull the handles. The fan is the resistance — don't death-grip a gear you can't finish.",
  }),
];
