import { labelsFor, type MuscleId } from "./muscles";
import type { ProgramDay, Workout } from "./types";

function split(
  row: Omit<Workout, "kind" | "muscles"> & {
    primary: MuscleId[];
    secondary?: MuscleId[];
  },
): Workout {
  return {
    ...row,
    kind: "split",
    muscles: labelsFor(row.primary, row.secondary),
  };
}

function program(
  row: Omit<Workout, "kind" | "muscles"> & {
    primary: MuscleId[];
    secondary?: MuscleId[];
    days: ProgramDay[];
  },
): Workout {
  return {
    ...row,
    kind: "program",
    muscles: labelsFor(row.primary, row.secondary),
  };
}

/** Common gym splits — PPL, upper/lower, bro days — plus the map of what each day trains. */
export const SPLIT_VIDEOS: Workout[] = [
  split({
    id: "split-ppl",
    title: "Push / pull / legs — the split explained",
    trainer: "Jeff Nippard",
    youtubeId: "qVek72z3F1U",
    minutes: 18,
    level: "Intermediate",
    kcal: 40,
    category: "PPL",
    equipment: ["Barbell", "Dumbbells"],
    primary: ["chest", "lats", "quads", "glutes", "front-delt", "biceps", "triceps"],
    secondary: ["hamstrings", "traps"],
    moves: ["Squat or hinge", "Horizontal + vertical push", "Horizontal + vertical pull", "Isolation for delts, arms, calves"],
    cue: "Six days if you recover. Three if you don't. Same patterns, less junk volume.",
    days: [
      { label: "Push", workoutId: "split-push" },
      { label: "Pull", workoutId: "split-pull" },
      { label: "Legs", workoutId: "split-legs" },
    ],
  }),
  split({
    id: "split-push",
    title: "PPL · Push day",
    trainer: "Jeff Nippard",
    youtubeId: "bvwg4D9UWGI",
    minutes: 16,
    level: "Intermediate",
    kcal: 220,
    category: "PPL",
    equipment: ["Barbell", "Cable", "Machine"],
    primary: ["chest", "front-delt", "triceps"],
    secondary: ["serratus"],
    pattern: "horizontal-push",
    prescription: "50–70 min in the gym",
    moves: ["Bench press", "Machine shoulder press", "Pec deck", "Cable lateral raise", "Overhead extension", "Tricep kickback"],
    alternatives: ["lift-bench", "lift-ohp", "lift-lateral", "lift-skull"],
    cue: "Chest first while you're fresh. Delts next. Triceps finish. Leave a rep in the tank on the last heavy press.",
  }),
  split({
    id: "split-pull",
    title: "PPL · Pull day",
    trainer: "Jeff Nippard",
    youtubeId: "spKGN0XzErU",
    minutes: 18,
    level: "Intermediate",
    kcal: 230,
    category: "PPL",
    equipment: ["Bar", "Cable", "Dumbbells"],
    primary: ["lats", "traps", "biceps"],
    secondary: ["hamstrings"],
    pattern: "horizontal-pull",
    prescription: "50–70 min in the gym",
    moves: ["Pulldown or pull-up", "Row", "Rear-delt work", "Face pull", "Curl"],
    alternatives: ["lift-pullup", "lift-row", "lift-facepull", "lift-bb-curl"],
    cue: "Width then thickness. Elbows to the hip. Rear delts before the biceps steal the set.",
  }),
  split({
    id: "split-legs",
    title: "PPL · Leg day",
    trainer: "Jeff Nippard",
    youtubeId: "RQNfBQbcbIo",
    minutes: 16,
    level: "Advanced",
    kcal: 280,
    category: "PPL",
    equipment: ["Barbell", "Machine"],
    primary: ["quads", "hamstrings", "glutes"],
    secondary: ["calves", "abs"],
    pattern: "squat",
    prescription: "55–75 min in the gym",
    moves: ["Leg extension", "Romanian deadlift", "Hip thrust", "Leg press", "Calf raise"],
    alternatives: ["lift-squat", "lift-bb-rdl", "lift-hip-thrust", "lift-calf"],
    cue: "Quads, hinge, glutes, press, calves. Hard sets, not a lot of them.",
  }),
  split({
    id: "split-upper",
    title: "Upper / lower · Upper day",
    trainer: "Caroline Girvan",
    youtubeId: "DE5FRnqc4S4",
    minutes: 45,
    level: "Intermediate",
    kcal: 320,
    category: "Upper/Lower",
    equipment: ["Dumbbells", "Mat"],
    primary: ["chest", "lats", "front-delt", "biceps", "triceps"],
    secondary: ["abs"],
    pattern: "horizontal-push",
    prescription: "Follow the film or 8–12 per move",
    moves: ["Row", "Chest press", "Push-up variations", "Pullover", "Fly", "Arnold press", "Skull crusher", "Curl"],
    alternatives: ["lift-row", "lift-bench", "lift-arnold", "lift-skull"],
    cue: "Push then pull, same session. Control the eccentric. Shoulders get the lighter bells.",
  }),
  split({
    id: "split-lower",
    title: "Upper / lower · Lower day",
    trainer: "Caroline Girvan",
    youtubeId: "hGaYKeFecM0",
    minutes: 46,
    level: "Advanced",
    kcal: 360,
    category: "Upper/Lower",
    equipment: ["Dumbbells", "Mat"],
    primary: ["quads", "glutes", "hamstrings"],
    secondary: ["calves", "abs"],
    pattern: "squat",
    prescription: "Follow the film or 8–12 per move",
    moves: ["Squat", "Lunge", "RDL", "Staggered squat", "Lateral lunge"],
    alternatives: ["lift-goblet", "lift-lunge", "lift-rdl"],
    cue: "Depth over load. Heel down. If the low back talks, drop the staple to bodyweight.",
  }),
  split({
    id: "split-chest",
    title: "Bro split · Chest",
    trainer: "Jeff Nippard",
    youtubeId: "LwHoNk-sjgs",
    minutes: 14,
    level: "Intermediate",
    kcal: 200,
    category: "Bro split",
    equipment: ["Barbell", "Dumbbells", "Cable"],
    primary: ["chest"],
    secondary: ["triceps", "front-delt"],
    pattern: "horizontal-push",
    prescription: "45–60 min",
    moves: ["Flat press", "Incline press", "Fly or crossover", "Dip or push-up finisher"],
    alternatives: ["lift-bench", "lift-incline", "lift-crossover", "lift-dip"],
    cue: "Heavy compound first. Incline while you're still honest. Isolation last.",
  }),
  split({
    id: "split-back",
    title: "Bro split · Back",
    trainer: "Jeff Nippard",
    youtubeId: "9B-5irFdB3c",
    minutes: 16,
    level: "Intermediate",
    kcal: 220,
    category: "Bro split",
    equipment: ["Bar", "Cable", "Dumbbells"],
    primary: ["lats", "traps"],
    secondary: ["biceps"],
    pattern: "vertical-pull",
    prescription: "50–65 min",
    moves: ["Vertical pull", "Horizontal row", "Chest-supported or T-bar", "Face pull", "Straight-arm"],
    alternatives: ["lift-pullup", "lift-row", "lift-facepull", "lift-straight-arm"],
    cue: "Width, thickness, rear delts. Don't let curls sneak in until the back is cooked.",
  }),
  split({
    id: "split-shoulders",
    title: "Bro split · Shoulders",
    trainer: "ScottHermanFitness",
    youtubeId: "2yjwXTZQDDI",
    minutes: 12,
    level: "Intermediate",
    kcal: 180,
    category: "Bro split",
    equipment: ["Barbell", "Dumbbells", "Cable"],
    primary: ["front-delt", "traps"],
    secondary: ["triceps"],
    pattern: "vertical-push",
    prescription: "40–55 min",
    moves: ["Overhead press", "Lateral raise", "Rear-delt fly", "Face pull", "Shrug"],
    alternatives: ["lift-ohp", "lift-lateral", "lift-rear-fly", "lift-shrug"],
    cue: "Press first. Laterals for width. Rear delts last so they actually get a turn.",
  }),
  split({
    id: "split-arms",
    title: "Bro split · Arms + abs",
    trainer: "Caroline Girvan",
    youtubeId: "U-OYrmX2-k0",
    minutes: 30,
    level: "Intermediate",
    kcal: 220,
    category: "Bro split",
    equipment: ["Dumbbells", "Mat"],
    primary: ["biceps", "triceps", "abs"],
    secondary: ["front-delt"],
    pattern: "isolation",
    prescription: "Follow the film",
    moves: ["Curl variations", "Diamond press", "Dips or chair dips", "Tricep push-up", "Core finisher"],
    alternatives: ["lift-bb-curl", "lift-skull", "lift-plank"],
    cue: "Alternate biceps and triceps so neither goes to junk form. Warm the shoulders before dips.",
  }),
  split({
    id: "split-triceps",
    title: "Bro split · Triceps pump",
    trainer: "ScottHermanFitness",
    youtubeId: "cXICnzp1mD8",
    minutes: 12,
    level: "Intermediate",
    kcal: 140,
    category: "Bro split",
    equipment: ["EZ bar", "Cable"],
    primary: ["triceps"],
    secondary: ["chest"],
    pattern: "isolation",
    prescription: "30–40 min",
    moves: ["Overhead extension", "Skull crusher", "Pushdown", "Reverse pushdown"],
    alternatives: ["lift-overhead-tri", "lift-skull", "lift-pushdown"],
    cue: "Heavy extensions first. Pushdowns as the burn set. Elbows don't wander.",
  }),
  split({
    id: "split-full-a",
    title: "Full body A · squat + press + row",
    trainer: "Caroline Girvan",
    youtubeId: "ScInpT_5dIQ",
    minutes: 15,
    level: "Beginner",
    kcal: 240,
    category: "Full body",
    equipment: ["Barbell", "Dumbbells"],
    primary: ["quads", "chest", "lats"],
    secondary: ["glutes", "triceps", "biceps"],
    pattern: "squat",
    prescription: "45–60 min · 3×/week with B",
    moves: ["Squat pattern", "Horizontal press", "Horizontal or vertical pull", "Hinge accessory", "Core"],
    alternatives: ["lift-squat", "lift-bench", "lift-row", "lift-rdl"],
    cue: "One hard compound per pattern. Leave isolation for the last ten minutes.",
  }),
  split({
    id: "split-full-b",
    title: "Full body B · hinge + push + pull",
    trainer: "Caroline Girvan",
    youtubeId: "GViX8riaHX4",
    minutes: 14,
    level: "Beginner",
    kcal: 240,
    category: "Full body",
    equipment: ["Barbell", "Dumbbells"],
    primary: ["hamstrings", "glutes", "front-delt", "lats"],
    secondary: ["quads", "triceps"],
    pattern: "hinge",
    prescription: "45–60 min · 3×/week with A",
    moves: ["Deadlift or RDL", "Overhead or incline press", "Pulldown or chin-up", "Lunge", "Carry"],
    alternatives: ["lift-deadlift", "lift-ohp", "lift-pulldown", "lift-farmer"],
    cue: "Hinge while you're fresh. Vertical push next. Walk out with a carry.",
  }),
  split({
    id: "split-calisthenics",
    title: "Calisthenics strength day",
    trainer: "Calisthenic Movement",
    youtubeId: "eGo4IYlbE5g",
    minutes: 20,
    level: "Intermediate",
    kcal: 200,
    category: "Calisthenics",
    equipment: ["Bar", "None"],
    primary: ["lats", "chest", "abs"],
    secondary: ["triceps", "biceps"],
    pattern: "vertical-pull",
    prescription: "40–55 min",
    moves: ["Pull-up or chin-up", "Push-up or dip", "Inverted row or pike push-up", "Hanging raise or hollow", "Pike or pistol work"],
    alternatives: ["lift-pullup", "lift-pushup", "lift-dip", "lift-hollow"],
    cue: "Skill first, then volume. Full range or a regression — not a kip.",
  }),
  split({
    id: "split-cali-push",
    title: "Calisthenics push + core",
    trainer: "Calisthenic Movement",
    youtubeId: "IODxDxX7oi4",
    minutes: 18,
    level: "Intermediate",
    kcal: 180,
    category: "Calisthenics",
    equipment: ["None", "Dip bars"],
    primary: ["chest", "triceps", "abs"],
    secondary: ["front-delt"],
    pattern: "horizontal-push",
    prescription: "40–50 min",
    moves: ["Push-up ladder", "Dips or bench dips", "Pike or HSPU work", "Hollow + plank", "Diamond push-up finisher"],
    alternatives: ["lift-pushup", "lift-dip", "lift-pike-push", "lift-hollow"],
    cue: "Lock the ribs. Full lockout. If the elbows flare, regress the angle.",
  }),
  split({
    id: "split-cali-legs",
    title: "Calisthenics legs + skill",
    trainer: "CrossFit",
    youtubeId: "qDcniqddTeE",
    minutes: 16,
    level: "Intermediate",
    kcal: 190,
    category: "Calisthenics",
    equipment: ["None"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    pattern: "squat",
    prescription: "40–50 min",
    moves: ["Pistol progressions", "Split squat or lunge", "Nordic or RDL if you have load", "Calf raises", "Hollow or L-sit"],
    alternatives: ["lift-pistol", "lift-bss", "lift-lunge", "lift-hollow"],
    cue: "Own the eccentric. Depth you can stand up from beats a crash at the bottom.",
  }),
];

export const PROGRAMS: Workout[] = [
  program({
    id: "prog-ppl6",
    title: "PPL · 6-day hypertrophy",
    trainer: "Pact",
    youtubeId: "qVek72z3F1U",
    minutes: 60,
    level: "Intermediate",
    kcal: 240,
    category: "PPL",
    equipment: ["Barbell", "Dumbbells", "Cable"],
    primary: ["chest", "lats", "quads", "glutes", "front-delt"],
    secondary: ["hamstrings", "biceps", "triceps"],
    prescription: "6 days · ~55 min",
    progression: "Add a set or 2.5 kg when you hit the top of the rep range two weeks running.",
    cue: "Push, pull, legs, repeat. Deload week 7 if sleep or joints start arguing.",
    days: [
      { label: "Mon · Push", workoutId: "split-push" },
      { label: "Tue · Pull", workoutId: "split-pull" },
      { label: "Wed · Legs", workoutId: "split-legs" },
      { label: "Thu · Push", workoutId: "split-push" },
      { label: "Fri · Pull", workoutId: "split-pull" },
      { label: "Sat · Legs", workoutId: "split-legs" },
    ],
  }),
  program({
    id: "prog-ppl3",
    title: "PPL · 3-day full pass",
    trainer: "Pact",
    youtubeId: "qVek72z3F1U",
    minutes: 55,
    level: "Beginner",
    kcal: 220,
    category: "PPL",
    equipment: ["Barbell", "Dumbbells"],
    primary: ["chest", "lats", "quads"],
    secondary: ["glutes", "front-delt"],
    prescription: "Mon / Wed / Fri",
    progression: "Graduate to the 6-day when you recover between the same muscle twice a week.",
    cue: "Same three days as the six-day, just once through. Perfect when life is loud.",
    days: [
      { label: "Mon · Push", workoutId: "split-push" },
      { label: "Wed · Pull", workoutId: "split-pull" },
      { label: "Fri · Legs", workoutId: "split-legs" },
    ],
  }),
  program({
    id: "prog-ul4",
    title: "Upper / lower · 4-day",
    trainer: "Pact",
    youtubeId: "DE5FRnqc4S4",
    minutes: 50,
    level: "Intermediate",
    kcal: 260,
    category: "Upper/Lower",
    equipment: ["Dumbbells", "Barbell"],
    primary: ["chest", "lats", "quads", "glutes"],
    secondary: ["hamstrings", "front-delt"],
    prescription: "Mon / Tue / Thu / Fri",
    cue: "Two upper, two lower. Weekend is for easy engine work or nothing.",
    days: [
      { label: "Mon · Upper", workoutId: "split-upper" },
      { label: "Tue · Lower", workoutId: "split-lower" },
      { label: "Thu · Upper", workoutId: "split-upper" },
      { label: "Fri · Lower", workoutId: "split-lower" },
    ],
  }),
  program({
    id: "prog-bro5",
    title: "Bro split · 5-day",
    trainer: "Pact",
    youtubeId: "LwHoNk-sjgs",
    minutes: 50,
    level: "Intermediate",
    kcal: 210,
    category: "Bro split",
    equipment: ["Barbell", "Dumbbells", "Cable"],
    primary: ["chest", "lats", "front-delt", "quads", "biceps"],
    secondary: ["triceps", "glutes"],
    prescription: "Mon–Fri · weekend off",
    cue: "One muscle family per day. Volume is the point. Don't add a sixth day until this one is honest.",
    days: [
      { label: "Mon · Chest", workoutId: "split-chest" },
      { label: "Tue · Back", workoutId: "split-back" },
      { label: "Wed · Shoulders", workoutId: "split-shoulders" },
      { label: "Thu · Arms", workoutId: "split-arms" },
      { label: "Fri · Legs", workoutId: "split-legs" },
    ],
  }),
  program({
    id: "prog-fb3",
    title: "Full body · 3-day starter",
    trainer: "Pact",
    youtubeId: "ScInpT_5dIQ",
    minutes: 50,
    level: "Beginner",
    kcal: 240,
    category: "Full body",
    equipment: ["Barbell", "Dumbbells"],
    primary: ["quads", "chest", "lats", "hamstrings"],
    secondary: ["glutes", "abs"],
    prescription: "Mon / Wed / Fri",
    progression: "When A and B both feel easy, move to upper/lower.",
    cue: "Every session hits squat, hinge, push, pull. The shortest path to being generally strong.",
    days: [
      { label: "Mon · A", workoutId: "split-full-a" },
      { label: "Wed · B", workoutId: "split-full-b" },
      { label: "Fri · A", workoutId: "split-full-a" },
    ],
  }),
  program({
    id: "prog-cali3",
    title: "Calisthenics · 3-day skill",
    trainer: "Pact",
    youtubeId: "eGo4IYlbE5g",
    minutes: 40,
    level: "Intermediate",
    kcal: 180,
    category: "Calisthenics",
    equipment: ["Bar", "None"],
    primary: ["lats", "chest", "abs", "quads"],
    secondary: ["triceps", "glutes"],
    prescription: "3 days · skill + strength",
    cue: "Pull-up and push-up quality over extra sets. Pistol and pike as skill finishers, not wreckers.",
    days: [
      { label: "Day 1 · Pull bias", workoutId: "split-calisthenics" },
      { label: "Day 2 · Push + core", workoutId: "split-cali-push" },
      { label: "Day 3 · Legs + skill", workoutId: "split-cali-legs" },
    ],
  }),
  program({
    id: "prog-busy2",
    title: "Busy week · 2-day full body",
    trainer: "Pact",
    youtubeId: "l9_SoClAO5g",
    minutes: 45,
    level: "Beginner",
    kcal: 220,
    category: "Full body",
    equipment: ["Dumbbells", "None"],
    primary: ["quads", "chest", "lats"],
    secondary: ["glutes", "abs"],
    prescription: "Any two days with 48h between",
    cue: "Don't skip because you can't do four. Two honest full-body days still move the needle.",
    days: [
      { label: "Day 1 · A", workoutId: "split-full-a" },
      { label: "Day 2 · B", workoutId: "split-full-b" },
    ],
  }),
  program({
    id: "prog-engine",
    title: "Engine + lift · hybrid week",
    trainer: "Pact",
    youtubeId: "ml6cT4AZdqI",
    minutes: 40,
    level: "Intermediate",
    kcal: 280,
    category: "Conditioning",
    equipment: ["Shoes", "Dumbbells"],
    primary: ["quads", "glutes", "chest"],
    secondary: ["abs", "calves"],
    prescription: "6 days mixing lift and engine",
    cue: "Lift when recovery is high. Zone-2 or a follow-along when it isn't. Don't HIIT on deadlift day.",
    days: [
      { label: "Mon · Full A", workoutId: "split-full-a" },
      { label: "Tue · Easy engine", workoutId: "session-zone2" },
      { label: "Wed · Full B", workoutId: "split-full-b" },
      { label: "Thu · Mobility", workoutId: "session-mobility" },
      { label: "Fri · Conditioning", workoutId: "hiit-cardio" },
      { label: "Sat · Long easy", workoutId: "session-yoga-30" },
    ],
  }),
];
